using System.Text;
using Quarry.Generators.Models;
using Quarry.Generators.Sql;
using Quarry;

namespace Quarry.Generators.Generation;

/// <summary>
/// Generates context class source code from context metadata.
/// </summary>
internal static class ContextCodeGenerator
{
    /// <summary>
    /// Generates the context class source code.
    /// </summary>
    public static string GenerateContextClass(ContextInfo context)
    {
        var sb = new StringBuilder();
        var access = "public";

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine("using Quarry.Internal;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(context.Namespace))
        {
            sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated partial class for {context.ClassName}.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"{access} partial class {context.ClassName}");
        sb.AppendLine("{");

        // Dialect field
        var dialectField = GetDialectField(context.Dialect);
        sb.AppendLine($"    private static readonly SqlDialect _dialect = {dialectField};");
        sb.AppendLine();

        // Schema name constant (if any)
        if (!string.IsNullOrEmpty(context.Schema))
        {
            sb.AppendLine($"    private const string _schemaName = \"{EscapeString(context.Schema!)}\";");
            sb.AppendLine();
        }

        // Constructors
        GenerateConstructors(sb, context, access);

        // Query builder properties
        foreach (var mapping in context.EntityMappings)
        {
            GenerateQueryBuilderProperty(sb, mapping, context.Schema, access);
        }

        // Insert methods
        foreach (var mapping in context.EntityMappings)
        {
            GenerateInsertMethods(sb, mapping, context.Schema, access);
        }

        // Update methods
        foreach (var mapping in context.EntityMappings)
        {
            GenerateUpdateMethod(sb, mapping, context.Schema, access);
        }

        // Generic Update<T>() override
        GenerateGenericUpdateMethod(sb, context.EntityMappings, context.Schema, access);

        // Generic Delete<T>() override
        GenerateGenericDeleteMethod(sb, context.EntityMappings, context.Schema, access);

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the constructors.
    /// </summary>
    private static void GenerateConstructors(StringBuilder sb, ContextInfo context, string access)
    {
        // Simple constructor
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates a new {context.ClassName} with the specified connection.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"connection\">The database connection to use.</param>");
        sb.AppendLine($"    {access} {context.ClassName}(IDbConnection connection)");
        sb.AppendLine($"        : base(connection)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Full constructor
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates a new {context.ClassName} with the specified connection and options.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"connection\">The database connection to use.</param>");
        sb.AppendLine($"    /// <param name=\"defaultTimeout\">Optional default timeout for queries.</param>");
        sb.AppendLine($"    /// <param name=\"defaultIsolation\">Optional default isolation level for transactions.</param>");
        sb.AppendLine($"    {access} {context.ClassName}(");
        sb.AppendLine($"        IDbConnection connection,");
        sb.AppendLine($"        TimeSpan? defaultTimeout,");
        sb.AppendLine($"        IsolationLevel? defaultIsolation = null)");
        sb.AppendLine($"        : base(connection, defaultTimeout, defaultIsolation)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a QueryBuilder factory method for an entity.
    /// </summary>
    private static void GenerateQueryBuilderProperty(StringBuilder sb, EntityMapping mapping, string? schemaName, string access)
    {
        var entity = mapping.Entity;
        var propertyName = mapping.PropertyName;

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets a query builder for the {entity.TableName} table.");
        sb.AppendLine($"    /// </summary>");

        // Pass 'this' as IQueryExecutionContext for query execution support
        if (!string.IsNullOrEmpty(schemaName))
        {
            sb.AppendLine($"    {access} partial IQueryBuilder<{entity.EntityName}> {propertyName}()");
            sb.AppendLine($"        => QueryBuilder<{entity.EntityName}>.Create(_dialect, \"{EscapeString(entity.TableName)}\", _schemaName, (IQueryExecutionContext)this);");
        }
        else
        {
            sb.AppendLine($"    {access} partial IQueryBuilder<{entity.EntityName}> {propertyName}()");
            sb.AppendLine($"        => QueryBuilder<{entity.EntityName}>.Create(_dialect, \"{EscapeString(entity.TableName)}\", null, (IQueryExecutionContext)this);");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Gets the dialect field expression for the specified dialect.
    /// </summary>
    private static string GetDialectField(SqlDialect dialect)
    {
        return dialect switch
        {
            SqlDialect.SQLite => "SqlDialect.SQLite",
            SqlDialect.PostgreSQL => "SqlDialect.PostgreSQL",
            SqlDialect.MySQL => "SqlDialect.MySQL",
            SqlDialect.SqlServer => "SqlDialect.SqlServer",
            _ => "SqlDialect.SQLite"
        };
    }

    /// <summary>
    /// Generates Insert methods for an entity.
    /// </summary>
    private static void GenerateInsertMethods(StringBuilder sb, EntityMapping mapping, string? schemaName, string access)
    {
        var entity = mapping.Entity;
        var entityName = entity.EntityName;
        var tableName = entity.TableName;
        var schemaArg = !string.IsNullOrEmpty(schemaName) ? "_schemaName" : "null";

        // Insert(entity) - single entity insert
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates an INSERT operation for a single {entityName}.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"entity\">The entity to insert.</param>");
        sb.AppendLine($"    /// <returns>An InsertBuilder for execution.</returns>");
        sb.AppendLine($"    {access} IInsertBuilder<{entityName}> Insert({entityName} entity)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return new InsertBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, (IQueryExecutionContext)this, entity);");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // InsertMany(entities) - batch insert
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates an INSERT operation for multiple {entityName} entities.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"entities\">The entities to insert.</param>");
        sb.AppendLine($"    /// <returns>An InsertBuilder for execution.</returns>");
        sb.AppendLine($"    {access} IInsertBuilder<{entityName}> InsertMany(IEnumerable<{entityName}> entities)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        var builder = new InsertBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, (IQueryExecutionContext)this);");
        sb.AppendLine($"        foreach (var entity in entities)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            builder.Values(entity);");
        sb.AppendLine($"        }}");
        sb.AppendLine($"        return builder;");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates an Update method for an entity.
    /// </summary>
    private static void GenerateUpdateMethod(StringBuilder sb, EntityMapping mapping, string? schemaName, string access)
    {
        var entity = mapping.Entity;
        var entityName = entity.EntityName;
        var tableName = entity.TableName;
        var schemaArg = !string.IsNullOrEmpty(schemaName) ? "_schemaName" : "null";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates an UPDATE operation for {entityName} entities.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <returns>An UpdateBuilder for building the update operation.</returns>");
        sb.AppendLine($"    /// <remarks>");
        sb.AppendLine($"    /// You must call Where() or All() before execution to prevent accidental updates.");
        sb.AppendLine($"    /// </remarks>");
        sb.AppendLine($"    {access} IUpdateBuilder<{entityName}> Update{entityName}()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return new UpdateBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, (IQueryExecutionContext)this);");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a generic Update&lt;T&gt;() method that overrides the base class placeholder.
    /// Routes to entity-specific implementations based on typeof(T).
    /// </summary>
    private static void GenerateGenericUpdateMethod(StringBuilder sb, IReadOnlyList<EntityMapping> mappings, string? schemaName, string access)
    {
        var schemaArg = !string.IsNullOrEmpty(schemaName) ? "_schemaName" : "null";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates an UPDATE operation for the specified entity type.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <typeparam name=\"T\">The entity type to update.</typeparam>");
        sb.AppendLine($"    /// <returns>An UpdateBuilder for building the update operation.</returns>");
        sb.AppendLine($"    {access} new IUpdateBuilder<T> Update<T>() where T : class");
        sb.AppendLine($"    {{");

        foreach (var mapping in mappings)
        {
            var entityName = mapping.Entity.EntityName;
            var tableName = mapping.Entity.TableName;
            sb.AppendLine($"        if (typeof(T) == typeof({entityName}))");
            sb.AppendLine($"            return (IUpdateBuilder<T>)(object)new UpdateBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, (IQueryExecutionContext)this);");
        }

        sb.AppendLine($"        throw new NotImplementedException($\"No update mapping for {{typeof(T).Name}}. Ensure the entity type is declared in this context.\");");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a generic Delete&lt;T&gt;() method that overrides the base class placeholder.
    /// Routes to entity-specific implementations based on typeof(T).
    /// </summary>
    private static void GenerateGenericDeleteMethod(StringBuilder sb, IReadOnlyList<EntityMapping> mappings, string? schemaName, string access)
    {
        var schemaArg = !string.IsNullOrEmpty(schemaName) ? "_schemaName" : "null";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates a DELETE operation for the specified entity type.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <typeparam name=\"T\">The entity type to delete.</typeparam>");
        sb.AppendLine($"    /// <returns>A DeleteBuilder for building the delete operation.</returns>");
        sb.AppendLine($"    {access} new IDeleteBuilder<T> Delete<T>() where T : class");
        sb.AppendLine($"    {{");

        foreach (var mapping in mappings)
        {
            var entityName = mapping.Entity.EntityName;
            var tableName = mapping.Entity.TableName;
            sb.AppendLine($"        if (typeof(T) == typeof({entityName}))");
            sb.AppendLine($"            return (IDeleteBuilder<T>)(object)new DeleteBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, (IQueryExecutionContext)this);");
        }

        sb.AppendLine($"        throw new NotImplementedException($\"No delete mapping for {{typeof(T).Name}}. Ensure the entity type is declared in this context.\");");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Escapes a string for use in C# source code.
    /// </summary>
    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}
