using System.Text;
using Quarry.Generators.Models;
using Quarry.Generators.Sql;
using Quarry;

namespace Quarry.Generators.Generation;

/// <summary>
/// Generates context class source code from context metadata.
/// </summary>
internal static class ContextCodeGenerator
{
    /// <summary>
    /// Generates the context class source code.
    /// </summary>
    public static string GenerateContextClass(ContextInfo context)
    {
        var sb = new StringBuilder();
        var access = "public";

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine("using Quarry.Internal;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(context.Namespace))
        {
            sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated partial class for {context.ClassName}.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"{access} partial class {context.ClassName}");
        sb.AppendLine("{");

        // Schema name constant (if any)
        if (!string.IsNullOrEmpty(context.Schema))
        {
            sb.AppendLine($"    private const string _schemaName = \"{EscapeString(context.Schema!)}\";");
            sb.AppendLine();
        }

        // Constructors
        GenerateConstructors(sb, context, access);

        // Query builder properties
        foreach (var mapping in context.EntityMappings)
        {
            GenerateQueryBuilderProperty(sb, mapping, context.Schema, access);
        }

        // CTE methods
        GenerateCteMethods(sb, context, access);

        // Insert/Update/Delete methods are now accessed via EntityAccessor:
        // db.Users().Insert(entity), db.Users().Update(), db.Users().Delete()

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the constructors.
    /// </summary>
    private static void GenerateConstructors(StringBuilder sb, ContextInfo context, string access)
    {
        // Simple constructor
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates a new {context.ClassName} with the specified connection.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"connection\">The database connection to use.</param>");
        sb.AppendLine($"    {access} {context.ClassName}(IDbConnection connection)");
        sb.AppendLine($"        : base(connection)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Owned connection constructor
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates a new {context.ClassName} with the specified connection and ownership flag.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"connection\">The database connection to use.</param>");
        sb.AppendLine($"    /// <param name=\"ownsConnection\">If true, the context will dispose the connection when disposed.</param>");
        sb.AppendLine($"    {access} {context.ClassName}(IDbConnection connection, bool ownsConnection)");
        sb.AppendLine($"        : base(connection, ownsConnection)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Full constructor
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates a new {context.ClassName} with the specified connection and options.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"connection\">The database connection to use.</param>");
        sb.AppendLine($"    /// <param name=\"ownsConnection\">If true, the context will dispose the connection when disposed.</param>");
        sb.AppendLine($"    /// <param name=\"defaultTimeout\">Optional default timeout for queries.</param>");
        sb.AppendLine($"    /// <param name=\"defaultIsolation\">Optional default isolation level for transactions.</param>");
        sb.AppendLine($"    {access} {context.ClassName}(");
        sb.AppendLine($"        IDbConnection connection,");
        sb.AppendLine($"        bool ownsConnection,");
        sb.AppendLine($"        TimeSpan? defaultTimeout,");
        sb.AppendLine($"        IsolationLevel? defaultIsolation = null)");
        sb.AppendLine($"        : base(connection, ownsConnection, defaultTimeout, defaultIsolation)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates an EntityAccessor factory method for an entity.
    /// </summary>
    private static void GenerateQueryBuilderProperty(StringBuilder sb, EntityMapping mapping, string? schemaName, string access)
    {
        var entity = mapping.Entity;
        var propertyName = mapping.PropertyName;

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets an entity accessor for the {entity.TableName} table.");
        sb.AppendLine($"    /// </summary>");

        sb.AppendLine($"    {access} partial IEntityAccessor<{entity.EntityName}> {propertyName}()");
        sb.AppendLine($"        => throw new NotSupportedException(\"Entity accessor methods must be intercepted by the Quarry source generator.\");");

        sb.AppendLine();
    }

    /// <summary>
    /// Generates CTE methods (With and FromCte) on the context class.
    /// With&lt;TDto&gt;() returns the context type itself so entity accessor methods
    /// and additional With() calls remain available for chaining.
    /// </summary>
    private static void GenerateCteMethods(StringBuilder sb, ContextInfo context, string access)
    {
        // With<TDto>(IQueryBuilder<TDto> innerQuery) — identity projection inner query
        // Always emitted: the generated shadow is required as the interceptor target.
        // When the context inherits QuarryContext<TSelf>, the `new` keyword remains valid
        // because it hides the inherited QuarryContext<TSelf>.With<TDto>. The generic base
        // ensures discovery resolves the chain correctly (its typed return is visible to the
        // SemanticModel), while this shadow provides the interceptable call target.
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Defines a Common Table Expression (CTE) from an inner query.");
        sb.AppendLine($"    /// The TDto class's public properties define the CTE's columns.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    {access} new {context.ClassName} With<TDto>(IQueryBuilder<TDto> innerQuery) where TDto : class");
        sb.AppendLine($"        => throw new NotSupportedException(\"CTE methods must be intercepted by the Quarry source generator.\");");
        sb.AppendLine();

        // With<TEntity, TDto>(IQueryBuilder<TEntity, TDto> innerQuery) — projected inner query
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Defines a Common Table Expression (CTE) from an inner query with a projection.");
        sb.AppendLine($"    /// The TDto class's public properties define the CTE's columns.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    {access} new {context.ClassName} With<TEntity, TDto>(IQueryBuilder<TEntity, TDto> innerQuery) where TEntity : class where TDto : class");
        sb.AppendLine($"        => throw new NotSupportedException(\"CTE methods must be intercepted by the Quarry source generator.\");");
        sb.AppendLine();

        // FromCte<TDto>() — use a previously defined CTE as the primary FROM source
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Starts a query from a previously defined CTE as the primary table.");
        sb.AppendLine($"    /// Must be preceded by a With&lt;TDto&gt;() call that defines the CTE.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    {access} new IEntityAccessor<TDto> FromCte<TDto>() where TDto : class");
        sb.AppendLine($"        => throw new NotSupportedException(\"CTE methods must be intercepted by the Quarry source generator.\");");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates an Update method for an entity.
    /// </summary>
    private static void GenerateUpdateMethod(StringBuilder sb, EntityMapping mapping, string? schemaName, string access)
    {
        var entity = mapping.Entity;
        var entityName = entity.EntityName;
        var tableName = entity.TableName;
        var schemaArg = !string.IsNullOrEmpty(schemaName) ? "_schemaName" : "null";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates an UPDATE operation for {entityName} entities.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <returns>An UpdateBuilder for building the update operation.</returns>");
        sb.AppendLine($"    /// <remarks>");
        sb.AppendLine($"    /// You must call Where() or All() before execution to prevent accidental updates.");
        sb.AppendLine($"    /// </remarks>");
        sb.AppendLine($"    {access} IUpdateBuilder<{entityName}> Update{entityName}()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return new UpdateBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, this);");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a generic Update&lt;T&gt;() method that overrides the base class placeholder.
    /// Routes to entity-specific implementations based on typeof(T).
    /// </summary>
    private static void GenerateGenericUpdateMethod(StringBuilder sb, IReadOnlyList<EntityMapping> mappings, string? schemaName, string access)
    {
        var schemaArg = !string.IsNullOrEmpty(schemaName) ? "_schemaName" : "null";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates an UPDATE operation for the specified entity type.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <typeparam name=\"T\">The entity type to update.</typeparam>");
        sb.AppendLine($"    /// <returns>An UpdateBuilder for building the update operation.</returns>");
        sb.AppendLine($"    {access} new IUpdateBuilder<T> Update<T>() where T : class");
        sb.AppendLine($"    {{");

        foreach (var mapping in mappings)
        {
            var entityName = mapping.Entity.EntityName;
            var tableName = mapping.Entity.TableName;
            sb.AppendLine($"        if (typeof(T) == typeof({entityName}))");
            sb.AppendLine($"            return (IUpdateBuilder<T>)(object)new UpdateBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, this);");
        }

        sb.AppendLine($"        throw new NotImplementedException($\"No update mapping for {{typeof(T).Name}}. Ensure the entity type is declared in this context.\");");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a generic Delete&lt;T&gt;() method that overrides the base class placeholder.
    /// Routes to entity-specific implementations based on typeof(T).
    /// </summary>
    private static void GenerateGenericDeleteMethod(StringBuilder sb, IReadOnlyList<EntityMapping> mappings, string? schemaName, string access)
    {
        var schemaArg = !string.IsNullOrEmpty(schemaName) ? "_schemaName" : "null";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Creates a DELETE operation for the specified entity type.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <typeparam name=\"T\">The entity type to delete.</typeparam>");
        sb.AppendLine($"    /// <returns>A DeleteBuilder for building the delete operation.</returns>");
        sb.AppendLine($"    {access} new IDeleteBuilder<T> Delete<T>() where T : class");
        sb.AppendLine($"    {{");

        foreach (var mapping in mappings)
        {
            var entityName = mapping.Entity.EntityName;
            var tableName = mapping.Entity.TableName;
            sb.AppendLine($"        if (typeof(T) == typeof({entityName}))");
            sb.AppendLine($"            return (IDeleteBuilder<T>)(object)new DeleteBuilder<{entityName}>(_dialect, \"{EscapeString(tableName)}\", {schemaArg}, this);");
        }

        sb.AppendLine($"        throw new NotImplementedException($\"No delete mapping for {{typeof(T).Name}}. Ensure the entity type is declared in this context.\");");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    /// <summary>
    /// Escapes a string for use in C# source code.
    /// </summary>
    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}
