using System.Text;
using Quarry.Generators.Models;
using Quarry.Shared.Migration;

namespace Quarry.Generators.Generation;

/// <summary>
/// Generates entity class source code from schema metadata.
/// </summary>
internal static class EntityCodeGenerator
{
    /// <summary>
    /// Generates the entity class source code.
    /// </summary>
    public static string GenerateEntityClass(EntityInfo entity, string contextNamespace)
    {
        var sb = new StringBuilder();
        var access = "public";

        // Use the context namespace for entity classes
        var entityNamespace = string.IsNullOrEmpty(contextNamespace)
            ? entity.SchemaNamespace
            : contextNamespace;

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(entityNamespace))
        {
            sb.AppendLine($"namespace {entityNamespace};");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated entity class for the {entity.TableName} table.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"{access} partial class {entity.EntityName}");
        sb.AppendLine("{");

        // Generate properties
        foreach (var column in entity.Columns)
        {
            GenerateColumnProperty(sb, column);
        }

        // Generate navigation properties
        foreach (var navigation in entity.Navigations)
        {
            GenerateNavigationProperty(sb, navigation);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a column property.
    /// </summary>
    private static void GenerateColumnProperty(StringBuilder sb, ColumnInfo column)
    {
        // Determine the accessor type
        var accessor = column.Modifiers.IsComputed ? "{ get; init; }" : "{ get; set; }";

        // Build the property type
        string propertyType;
        string? defaultValue = null;

        switch (column.Kind)
        {
            case ColumnKind.ForeignKey:
                // EntityRef<TEntity, TKey> properties
                propertyType = $"EntityRef<{column.ReferencedEntityName}, {GetNullableType(column.FullClrType, column.IsNullable)}>";
                break;

            case ColumnKind.PrimaryKey:
            case ColumnKind.Standard:
            default:
                propertyType = GetNullableType(column.FullClrType, column.IsNullable);
                // Add null! default for non-nullable strings to suppress warnings
                if (column.FullClrType == "string" && !column.IsNullable)
                {
                    defaultValue = "null!";
                }
                break;
        }

        // XML documentation
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets or sets the {column.PropertyName} column value.");
        sb.AppendLine($"    /// </summary>");

        if (column.Modifiers.IsIdentity)
        {
            sb.AppendLine($"    /// <remarks>Auto-increment identity column.</remarks>");
        }
        else if (column.Modifiers.IsComputed)
        {
            sb.AppendLine($"    /// <remarks>Computed column (read-only).</remarks>");
        }
        else if (column.Kind == ColumnKind.ForeignKey)
        {
            sb.AppendLine($"    /// <remarks>Foreign key to {column.ReferencedEntityName}. Access .Id for the key value, .Value for the navigation.</remarks>");
        }

        // Property declaration
        if (defaultValue is not null)
        {
            sb.AppendLine($"    public {propertyType} {column.PropertyName} {accessor} = {defaultValue};");
        }
        else
        {
            sb.AppendLine($"    public {propertyType} {column.PropertyName} {accessor}");
        }
    }

    /// <summary>
    /// Generates a navigation property.
    /// </summary>
    private static void GenerateNavigationProperty(StringBuilder sb, NavigationInfo navigation)
    {
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets the collection of related {navigation.RelatedEntityName} entities.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <remarks>");
        sb.AppendLine($"    /// Check IsLoaded property to verify the collection has been populated via a join.");
        sb.AppendLine($"    /// </remarks>");
        sb.AppendLine($"    public NavigationList<{navigation.RelatedEntityName}> {navigation.PropertyName} {{ get; internal set; }} = NavigationList<{navigation.RelatedEntityName}>.Unloaded();");
    }

    /// <summary>
    /// Gets the type string with nullable annotation if needed.
    /// </summary>
    private static string GetNullableType(string typeName, bool isNullable)
    {
        if (!isNullable)
            return typeName;

        // Don't add ? if the type already has it
        if (typeName.EndsWith("?"))
            return typeName;

        // Value types need Nullable<T> or T?
        // Reference types just need T?
        return typeName + "?";
    }
}
