using System.Text;
using Quarry.Generators.Models;
using Quarry.Shared.Migration;

namespace Quarry.Generators.Generation;

/// <summary>
/// Generates entity class source code from schema metadata.
/// </summary>
internal static class EntityCodeGenerator
{
    /// <summary>
    /// Generates the entity class source code.
    /// </summary>
    public static string GenerateEntityClass(EntityInfo entity, string contextNamespace)
    {
        var sb = new StringBuilder();
        var access = "public";

        // Use the context namespace for entity classes
        var entityNamespace = string.IsNullOrEmpty(contextNamespace)
            ? entity.SchemaNamespace
            : contextNamespace;

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(entityNamespace))
        {
            sb.AppendLine($"namespace {entityNamespace};");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated entity class for the {entity.TableName} table.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"{access} partial class {entity.EntityName}");
        sb.AppendLine("{");

        // Generate properties
        foreach (var column in entity.Columns)
        {
            GenerateColumnProperty(sb, column);
        }

        // Generate navigation properties
        foreach (var navigation in entity.Navigations)
        {
            GenerateNavigationProperty(sb, navigation);
        }

        // Generate singular navigation properties (One<T>)
        foreach (var singleNav in entity.SingleNavigations)
        {
            GenerateSingleNavigationProperty(sb, singleNav);
        }

        // Generate the nested Patch struct used by Update().Set(Entity.Patch)
        // and Update().Set(PatchAction<Entity.Patch>) partial-update overloads.
        // Returns silently if there are zero updatable columns or if the count
        // exceeds the 64-bit __mask cap — QRY045 reporting happens at the
        // generator entry point (QuarryGenerator) where SourceProductionContext
        // is available.
        GeneratePatchStruct(sb, entity);

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Returns the count of columns that participate in a Patch struct — i.e. columns
    /// that are neither Identity nor Computed. Mirrors the filter used by
    /// <c>InsertInfo.FromEntityInfo</c> / <c>PatchInfo.FromEntityInfo</c>.
    /// </summary>
    public static int CountUpdatableColumns(EntityInfo entity)
    {
        int count = 0;
        foreach (var c in entity.Columns)
        {
            if (c.Modifiers.IsIdentity) continue;
            if (c.Modifiers.IsComputed) continue;
            count++;
        }
        return count;
    }

    /// <summary>The hard cap on updatable columns per entity for Patch generation; see QRY045.</summary>
    public const int PatchColumnLimit = 64;

    /// <summary>
    /// True when the entity has a column named "Patch" — its property would
    /// collide with the nested struct's default name (CS0102).
    /// <see cref="ResolvePatchStructName(EntityInfo)"/> auto-renames the struct
    /// with leading underscores to avoid the collision; this helper drives the
    /// QRY047 reporting at the generator entry point.
    /// </summary>
    public static bool HasPatchNameCollision(EntityInfo entity)
    {
        foreach (var c in entity.Columns)
        {
            if (c.PropertyName == "Patch") return true;
        }
        return false;
    }

    /// <summary>Hard limit on leading underscores when resolving the nested
    /// Patch struct name. If the entity has columns named <c>Patch</c>,
    /// <c>_Patch</c>, <c>__Patch</c>, ... up to this depth, the generator gives
    /// up and suppresses Patch struct emission entirely.</summary>
    private const int MaxPatchRenamePrefixUnderscores = 4;

    /// <summary>
    /// Picks the name for the nested Patch struct on this entity. Default is
    /// <c>"Patch"</c>; if a column property of that name exists, prepends a
    /// leading underscore (<c>"_Patch"</c>) and repeats until no collision —
    /// up to <see cref="MaxPatchRenamePrefixUnderscores"/> underscores. Returns
    /// null when even the maximally-prefixed name collides; in that case
    /// callers suppress Patch struct emission and the diagnostic surface
    /// (QRY047) flags the entity as ineligible.
    /// </summary>
    public static string? ResolvePatchStructName(EntityInfo entity)
    {
        var columnNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var c in entity.Columns)
            columnNames.Add(c.PropertyName);

        var name = "Patch";
        int underscores = 0;
        while (columnNames.Contains(name))
        {
            if (underscores >= MaxPatchRenamePrefixUnderscores) return null;
            name = "_" + name;
            underscores++;
        }
        return name;
    }

    private static void GeneratePatchStruct(StringBuilder sb, EntityInfo entity)
    {
        var updatable = new List<ColumnInfo>();
        foreach (var c in entity.Columns)
        {
            if (c.Modifiers.IsIdentity) continue;
            if (c.Modifiers.IsComputed) continue;
            updatable.Add(c);
        }

        // No updatable columns → no Patch struct.
        if (updatable.Count == 0) return;

        // Over the ulong mask cap → no Patch struct (QRY045 reported separately).
        if (updatable.Count > PatchColumnLimit) return;

        // Column-name collision check: if the entity has a column named "Patch",
        // the resolver picks "_Patch" (or more underscores until unique). If even
        // the maximum-prefixed name collides, the resolver returns null and we
        // suppress emission entirely. QRY047 surfaces the rename / suppression.
        var structName = ResolvePatchStructName(entity);
        if (structName is null) return;

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Mutable partial-update payload for {entity.EntityName}. Property setters track which");
        sb.AppendLine("    /// fields were assigned via the <c>__mask</c> bitmask; the chain runtime reads the mask");
        sb.AppendLine("    /// at execute time to emit a SET clause covering only the touched columns.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// Reading a property that has not been assigned returns the field's default value");
        sb.AppendLine("    /// — Patch instances are intended for write-up assembly, not arbitrary read-back.");
        if (structName != "Patch")
            sb.AppendLine($"    /// <para>This struct is named <c>{structName}</c> instead of <c>Patch</c> because the entity has a column named <c>Patch</c> that would otherwise collide. Reference it as <c>{entity.EntityName}.{structName}</c>; see QRY047.</para>");
        sb.AppendLine("    /// </remarks>");
        // The IPatchFor<TEntity> marker constrains the partial-update Set
        // overloads on IUpdateBuilder<T> / IExecutableUpdateBuilder<T> so the
        // C# compiler rejects cross-entity patches at the call site.
        sb.AppendLine($"    public struct {structName} : Quarry.IPatchFor<{entity.EntityName}>");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Bitmask of assigned columns; bit position matches the column's order in the entity schema (excluding Identity and Computed).</summary>");
        sb.AppendLine("        internal ulong __mask;");

        // Mask bit constants — grouped together for readability and to keep
        // bit-position assignment obviously tied to declaration order.
        sb.AppendLine();
        for (int i = 0; i < updatable.Count; i++)
        {
            var col = updatable[i];
            var hex = $"0x{(1UL << i):X}UL";
            sb.AppendLine($"        internal const ulong _Mask_{col.PropertyName} = {hex};");
        }

        // Tracked properties.
        foreach (var col in updatable)
        {
            GeneratePatchProperty(sb, col);
        }

        sb.AppendLine("    }");
    }

    private static void GeneratePatchProperty(StringBuilder sb, ColumnInfo column)
    {
        // Compute the public property type using the same rules as the entity
        // property (FK → EntityRef<T,K>, otherwise the column's CLR type with
        // nullable annotation if appropriate).
        string propertyType;
        switch (column.Kind)
        {
            case ColumnKind.ForeignKey:
                propertyType = $"EntityRef<{column.ReferencedEntityName}, {GetNullableType(column.FullClrType, column.IsNullable)}>";
                break;
            case ColumnKind.PrimaryKey:
            case ColumnKind.Standard:
            default:
                propertyType = GetNullableType(column.FullClrType, column.IsNullable);
                break;
        }

        // Backing field: for non-nullable reference types, declare as nullable
        // (T?) to satisfy CS8618 without an initializer (struct instance fields
        // can't have initializers prior to C# 11+). The property getter then
        // suppresses the nullability with `!` — reading an unset reference-
        // typed property returns null (default(T)), matching struct semantics.
        // Use the column's authoritative IsValueType from semantic analysis
        // rather than the IsReferenceTypeName name-heuristic, which mis-
        // classifies user-defined structs (e.g. custom-mapped value types) as
        // reference types.
        bool isNonNullableReference =
            column.Kind != ColumnKind.ForeignKey                // EntityRef<,> is itself a struct
            && !column.IsNullable
            && !column.IsValueType;

        string fieldType = isNonNullableReference ? propertyType + "?" : propertyType;
        string getterExpr = isNonNullableReference ? $"__{column.PropertyName}!" : $"__{column.PropertyName}";

        sb.AppendLine();
        sb.AppendLine($"        private {fieldType} __{column.PropertyName};");
        sb.AppendLine($"        /// <summary>Gets or sets the {column.PropertyName} value. Setting flips <c>_Mask_{column.PropertyName}</c> in <c>__mask</c>.</summary>");
        if (column.Modifiers.IsSensitive)
            sb.AppendLine($"        /// <remarks>Column is marked sensitive in the schema (<c>Sensitive()</c>). Bound parameter values are redacted in diagnostic / trace output.</remarks>");
        sb.AppendLine($"        public {propertyType} {column.PropertyName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            get => {getterExpr};");
        sb.AppendLine($"            set {{ __{column.PropertyName} = value; __mask |= _Mask_{column.PropertyName}; }}");
        sb.AppendLine("        }");
    }

    /// <summary>
    /// Generates a column property.
    /// </summary>
    private static void GenerateColumnProperty(StringBuilder sb, ColumnInfo column)
    {
        // Determine the accessor type
        var accessor = column.Modifiers.IsComputed ? "{ get; init; }" : "{ get; set; }";

        // Build the property type
        string propertyType;
        string? defaultValue = null;

        switch (column.Kind)
        {
            case ColumnKind.ForeignKey:
                // EntityRef<TEntity, TKey> properties
                propertyType = $"EntityRef<{column.ReferencedEntityName}, {GetNullableType(column.FullClrType, column.IsNullable)}>";
                break;

            case ColumnKind.PrimaryKey:
            case ColumnKind.Standard:
            default:
                propertyType = GetNullableType(column.FullClrType, column.IsNullable);
                // Add default! for non-nullable reference types to suppress CS8618
                if (!column.IsNullable && CodeGen.CarrierAnalyzer.IsReferenceTypeName(column.FullClrType))
                {
                    defaultValue = "default!";
                }
                break;
        }

        // XML documentation
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets or sets the {column.PropertyName} column value.");
        sb.AppendLine($"    /// </summary>");

        if (column.Modifiers.IsIdentity)
        {
            sb.AppendLine($"    /// <remarks>Auto-increment identity column.</remarks>");
        }
        else if (column.Modifiers.IsComputed)
        {
            sb.AppendLine($"    /// <remarks>Computed column (read-only).</remarks>");
        }
        else if (column.Kind == ColumnKind.ForeignKey)
        {
            sb.AppendLine($"    /// <remarks>Foreign key to {column.ReferencedEntityName}. Access .Id for the key value, .Value for the navigation.</remarks>");
        }

        // Property declaration
        if (defaultValue is not null)
        {
            sb.AppendLine($"    public {propertyType} {column.PropertyName} {accessor} = {defaultValue};");
        }
        else
        {
            sb.AppendLine($"    public {propertyType} {column.PropertyName} {accessor}");
        }
    }

    /// <summary>
    /// Generates a navigation property.
    /// </summary>
    private static void GenerateNavigationProperty(StringBuilder sb, NavigationInfo navigation)
    {
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets the collection of related {navigation.RelatedEntityName} entities.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <remarks>");
        sb.AppendLine($"    /// Check IsLoaded property to verify the collection has been populated via a join.");
        sb.AppendLine($"    /// </remarks>");
        sb.AppendLine($"    public NavigationList<{navigation.RelatedEntityName}> {navigation.PropertyName} {{ get; internal set; }} = NavigationList<{navigation.RelatedEntityName}>.Unloaded();");
    }

    /// <summary>
    /// Generates a singular navigation property for One&lt;T&gt;.
    /// </summary>
    private static void GenerateSingleNavigationProperty(StringBuilder sb, SingleNavigationInfo navigation)
    {
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets the related {navigation.TargetEntityName} entity.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <remarks>");
        sb.AppendLine($"    /// This property is null unless the query includes a join to the {navigation.TargetEntityName} entity.");
        sb.AppendLine($"    /// </remarks>");
        sb.AppendLine($"    public {navigation.TargetEntityName}? {navigation.PropertyName} {{ get; internal set; }}");
    }

    /// <summary>
    /// Gets the type string with nullable annotation if needed.
    /// </summary>
    private static string GetNullableType(string typeName, bool isNullable)
    {
        if (!isNullable)
            return typeName;

        // Don't add ? if the type already has it
        if (typeName.EndsWith("?"))
            return typeName;

        // Value types need Nullable<T> or T?
        // Reference types just need T?
        return typeName + "?";
    }
}
