using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Quarry.Generators.Models;
using Quarry.Generators.Sql;
using Quarry;
using Quarry.Generators.Projection;
using Quarry.Generators.Translation;

namespace Quarry.Generators.Generation;

/// <summary>
/// Generates interceptor source code for Quarry method call sites.
/// </summary>
/// <remarks>
/// Interceptors use the [InterceptsLocation] attribute to redirect method calls
/// to generated code that provides compile-time SQL generation and typed reader delegates.
/// All interceptors use the 'file' scope modifier to prevent visibility to end users.
/// </remarks>
internal static partial class InterceptorCodeGenerator
{
    /// <summary>
    /// Generates the interceptors file for a context.
    /// </summary>
    public static string GenerateInterceptorsFile(
        string contextClassName,
        string? contextNamespace,
        string fileTag,
        IReadOnlyList<UsageSiteInfo> usageSites,
        IReadOnlyList<PrebuiltChainInfo>? prebuiltChains = null)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8602 // Dereference of a possibly null reference.");
        sb.AppendLine();

        // Required usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine("using Quarry.Internal;");
        sb.AppendLine("using Quarry.Logging;");
        sb.AppendLine("using Logsmith;");

        // Collect all unique entity type namespaces
        var entityNamespaces = usageSites
            .Select(s => GetNamespaceFromTypeName(s.EntityTypeName))
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct()
            .ToList();

        // Also collect namespaces from the source file of each usage site
        // This helps when entity types are from generated files in the same generator run
        var fileNamespaces = usageSites
            .Select(s => GetNamespaceFromFilePath(s.InvocationSyntax))
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct();

        // Collect context namespaces — generated entity types live in the context's namespace
        var contextNamespaces = usageSites
            .Select(s => s.ContextNamespace)
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct();

        // Collect entity schema namespaces from prebuilt chains — when entity types are error
        // types (unresolved during first compilation pass), the schema namespace from entity
        // metadata provides the using directive needed for cross-namespace resolution.
        var chainSchemaNamespaces = prebuiltChains != null
            ? prebuiltChains
                .Select(c => c.EntitySchemaNamespace)
                .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
                .Distinct()
            : Enumerable.Empty<string?>();

        var allNamespaces = entityNamespaces
            .Concat(fileNamespaces)
            .Concat(contextNamespaces!)
            .Concat(chainSchemaNamespaces!)
            .Distinct()
            .OrderBy(ns => ns);

        foreach (var ns in allNamespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();

        // InterceptsLocation attribute definition
        // Uses new format with (int version, string data)
        GenerateInterceptsLocationAttribute(sb);
        sb.AppendLine();

        // Namespace - interceptors must not be in global namespace
        // Use block namespace (not file-scoped) since we already have a block namespace for the attribute
        var interceptorNamespace = !string.IsNullOrEmpty(contextNamespace)
            ? contextNamespace
            : "Quarry.Generated";
        sb.AppendLine($"namespace {interceptorNamespace}");
        sb.AppendLine("{");
        sb.AppendLine();

        // Pass 1: Build carrier class infos for carrier-eligible chains and emit at namespace scope
        var carrierLookup = new Dictionary<string, (CarrierClassInfo Carrier, PrebuiltChainInfo Chain)>();
        var carrierClauseLookup = new Dictionary<string, (CarrierClassInfo Carrier, PrebuiltChainInfo Chain)>();
        var carrierFirstClauseIds = new HashSet<string>();
        if (prebuiltChains != null)
        {
            var carrierIndex = 0;
            foreach (var chain in prebuiltChains)
            {
                if (!chain.IsCarrierEligible)
                    continue;

                // With ChainRoot as carrier entry point, conditional first clauses are OK.
                // The ChainRoot is always unconditional (entity factory method on context).
                // Only skip if there's NO ChainRoot clause (shouldn't happen for direct fluent chains).
                var hasChainRoot = chain.Analysis.Clauses.Any(c => c.Role == ClauseRole.ChainRoot);
                if (!hasChainRoot && chain.Analysis.Clauses.Count > 0 && chain.Analysis.Clauses[0].IsConditional)
                    continue;

                // Validate execution terminal would be emitted — if not, carrier clause
                // interceptors would create carriers with no terminal to consume them.
                if (!WouldExecutionTerminalBeEmitted(chain))
                    continue;

                var resolvedBase = ResolveCarrierBaseClass(chain);
                var carrier = CarrierClassBuilder.Build(chain, carrierIndex, resolvedBase);
                if (carrier == null)
                    continue;

                carrierLookup[chain.Analysis.ExecutionSite.UniqueId] = (carrier, chain);
                foreach (var clause in chain.Analysis.Clauses)
                {
                    carrierClauseLookup[clause.Site.UniqueId] = (carrier, chain);
                }

                // With ChainRoot creating the carrier, no clause is "first in chain" for
                // carrier creation. The ChainRoot interceptor handles carrier creation.
                // Find the ChainRoot clause and mark it as the carrier entry point.
                var chainRootClause = chain.Analysis.Clauses
                    .FirstOrDefault(c => c.Role == ClauseRole.ChainRoot);
                if (chainRootClause != null)
                {
                    carrierFirstClauseIds.Add(chainRootClause.Site.UniqueId);
                }
                else if (chain.Analysis.Clauses.Count > 0)
                {
                    // Fallback: no ChainRoot (shouldn't happen for carrier chains)
                    carrierFirstClauseIds.Add(chain.Analysis.Clauses[0].Site.UniqueId);
                }

                EmitCarrierClass(sb, carrier);
                carrierIndex++;
            }
        }

        // File-scoped interceptor class
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated interceptors for {contextClassName} query methods.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"file static class {contextClassName}Interceptors_{fileTag}");
        sb.AppendLine("{");

        // Build chain analysis lookups for execution interceptor generation
        var chainLookup = new Dictionary<string, PrebuiltChainInfo>();
        var clauseBitMap = new Dictionary<string, int>(); // site UniqueId → bit index
        var chainMemberIds = new HashSet<string>(); // all site UniqueIds that are part of analyzed chains
        if (prebuiltChains != null)
        {
            foreach (var chain in prebuiltChains)
            {
                chainLookup[chain.Analysis.ExecutionSite.UniqueId] = chain;
                chainMemberIds.Add(chain.Analysis.ExecutionSite.UniqueId);
                foreach (var clause in chain.Analysis.Clauses)
                {
                    chainMemberIds.Add(clause.Site.UniqueId);
                    if (clause.IsConditional && clause.BitIndex.HasValue)
                    {
                        clauseBitMap[clause.Site.UniqueId] = clause.BitIndex.Value;
                    }
                }
            }
        }

        // Build clause → chain lookup for simplified clause interceptors in prebuilt chains
        var chainClauseLookup = new Dictionary<string, PrebuiltChainInfo>();
        var firstClauseIds = new HashSet<string>();
        if (prebuiltChains != null)
        {
            foreach (var chain in prebuiltChains)
            {
                foreach (var clause in chain.Analysis.Clauses)
                {
                    chainClauseLookup[clause.Site.UniqueId] = chain;
                }
                if (chain.Analysis.Clauses.Count > 0)
                {
                    // For non-carrier chains where the first clause is ChainRoot (which gets
                    // skipped on the non-carrier path), the first REAL clause after it needs
                    // to be treated as the chain entry so it emits AllocatePrebuiltParams.
                    var firstClause = chain.Analysis.Clauses[0];
                    firstClauseIds.Add(firstClause.Site.UniqueId);
                    if (firstClause.Role == ClauseRole.ChainRoot
                        && !carrierClauseLookup.ContainsKey(firstClause.Site.UniqueId)
                        && chain.Analysis.Clauses.Count > 1)
                    {
                        firstClauseIds.Add(chain.Analysis.Clauses[1].Site.UniqueId);
                    }
                }
            }
        }

        // Collect all static fields needed for cached extractors
        var carrierMemberIds = new HashSet<string>(carrierClauseLookup.Keys);
        var staticFields = CollectStaticFields(usageSites, chainMemberIds);

        // Collect all unique TypeMapping classes used across all usage sites
        var mappingInstances = CollectMappingInstances(usageSites, chainMemberIds);

        // Collect all unique EntityReader classes used across all usage sites
        var entityReaderInstances = CollectEntityReaderInstances(usageSites, chainMemberIds);

        // Filter out carrier member FieldInfo fields — those live on the carrier class now
        var interceptorStaticFields = staticFields
            .Where(f => f.SiteUniqueId == null || !carrierMemberIds.Contains(f.SiteUniqueId))
            .ToList();

        if (interceptorStaticFields.Count > 0 || mappingInstances.Count > 0 || entityReaderInstances.Count > 0)
        {
            sb.AppendLine("    #region Cached Fields");
            sb.AppendLine();
            foreach (var field in interceptorStaticFields)
            {
                sb.AppendLine($"    private static FieldInfo? {field.FieldName};");
            }
            foreach (var mapping in mappingInstances)
            {
                sb.AppendLine($"    private static readonly {mapping.Value} {mapping.Key} = new();");
            }
            foreach (var reader in entityReaderInstances)
            {
                sb.AppendLine($"    private static readonly {reader.Value} {reader.Key} = new();");
            }
            sb.AppendLine();
            sb.AppendLine("    #endregion");
            sb.AppendLine();
        }

        // Build the filtered list of sites for generation
        var allSitesForGeneration = usageSites
            .Where(s => s.IsAnalyzable || chainMemberIds.Contains(s.UniqueId))
            .ToList();

        // Group interceptors by chain (execution terminal → all clause sites in that chain)
        // Sites not part of any chain go into a "Standalone" group
        var processedSiteIds = new HashSet<string>();
        var chainGroups = new List<(string Label, List<UsageSiteInfo> Sites)>();
        var siteByUniqueId = allSitesForGeneration.ToDictionary(s => s.UniqueId);

        if (prebuiltChains != null)
        {
            foreach (var chain in prebuiltChains)
            {
                var chainSites = new List<UsageSiteInfo>();
                // Add clause sites in chain order
                foreach (var clause in chain.Analysis.Clauses)
                {
                    if (siteByUniqueId.TryGetValue(clause.Site.UniqueId, out var matchingSite))
                    {
                        chainSites.Add(matchingSite);
                        processedSiteIds.Add(matchingSite.UniqueId);
                    }
                }
                // Add execution site
                if (siteByUniqueId.TryGetValue(chain.Analysis.ExecutionSite.UniqueId, out var execSite))
                {
                    chainSites.Add(execSite);
                    processedSiteIds.Add(execSite.UniqueId);
                }

                if (chainSites.Count > 0)
                {
                    var execMethod = chain.Analysis.ExecutionSite.MethodName;
                    var label = $"Chain: {execMethod} at line {chain.Analysis.ExecutionSite.Line}";
                    chainGroups.Add((label, chainSites));
                }
            }
        }

        // Remaining sites not part of any chain
        var standaloneSites = allSitesForGeneration
            .Where(s => !processedSiteIds.Contains(s.UniqueId))
            .ToList();

        if (standaloneSites.Count > 0)
        {
            chainGroups.Add(("Standalone Interceptors", standaloneSites));
        }

        // Pre-group static fields by method name to avoid repeated linear scans
        var staticFieldsByMethod = new Dictionary<string, List<CachedExtractorField>>();
        foreach (var f in staticFields)
        {
            if (!staticFieldsByMethod.TryGetValue(f.MethodName, out var list))
            {
                list = new List<CachedExtractorField>();
                staticFieldsByMethod[f.MethodName] = list;
            }
            list.Add(f);
        }

        // Generate grouped output
        foreach (var (label, sites) in chainGroups)
        {
            sb.AppendLine($"    #region {label}");
            sb.AppendLine();
            foreach (var site in sites)
            {
                GenerateInterceptorMethod(sb, site, staticFields, staticFieldsByMethod, chainLookup, clauseBitMap, chainClauseLookup, firstClauseIds, carrierLookup, carrierClauseLookup, carrierFirstClauseIds);
            }
            sb.AppendLine($"    #endregion");
            sb.AppendLine();
        }

        sb.AppendLine("}"); // Close interceptor class
        sb.AppendLine("}"); // Close namespace

        return sb.ToString();
    }

    /// <summary>
    /// Represents a static field for caching a FieldInfo used for parameter extraction.
    /// </summary>
    private sealed class CachedExtractorField
    {
        public CachedExtractorField(
            string fieldName,
            string methodName,
            int parameterIndex,
            string expressionPath,
            string? siteUniqueId = null)
        {
            FieldName = fieldName;
            MethodName = methodName;
            ParameterIndex = parameterIndex;
            ExpressionPath = expressionPath;
            SiteUniqueId = siteUniqueId;
        }

        public string FieldName { get; }
        public string MethodName { get; }
        public int ParameterIndex { get; }
        /// <summary>Raw dot-separated path like "Body.Right" or "Body.Arguments[0]".</summary>
        public string ExpressionPath { get; }
        /// <summary>The unique ID of the usage site this field belongs to.</summary>
        public string? SiteUniqueId { get; }
    }

    /// <summary>
    /// Collects all static fields needed for cached extractors across all usage sites.
    /// </summary>
    private static List<CachedExtractorField> CollectStaticFields(IReadOnlyList<UsageSiteInfo> usageSites, HashSet<string> chainMemberIds)
    {
        var fields = new List<CachedExtractorField>();

        foreach (var site in usageSites.Where(s => s.IsAnalyzable || chainMemberIds.Contains(s.UniqueId)))
        {
            var methodName = $"{site.MethodName}_{site.UniqueId}";

            // Skip sites that won't generate captured parameter extraction
            if (site.Kind == InterceptorKind.Select && ShouldSkipSelectInterceptor(site))
                continue;

            var clauseInfo = site.ClauseInfo;
            if (clauseInfo == null || !clauseInfo.IsSuccess)
                continue;

            var capturedParams = clauseInfo.Parameters
                .Where(p => p.IsCaptured && p.CanGenerateDirectPath && !p.IsCollection)
                .ToList();
            foreach (var param in capturedParams)
            {
                var fieldName = $"_{methodName}_p{param.Index}";
                fields.Add(new CachedExtractorField(
                    fieldName,
                    methodName,
                    param.Index,
                    param.ExpressionPath!,
                    siteUniqueId: site.UniqueId));
            }
        }

        return fields;
    }

    /// <summary>
    /// Collects all unique TypeMapping class FQNs used across all usage sites and returns
    /// a mapping from field name to FQN for generating cached static readonly instances.
    /// </summary>
    private static Dictionary<string, string> CollectMappingInstances(IReadOnlyList<UsageSiteInfo> usageSites, HashSet<string> chainMemberIds)
    {
        var mappings = new Dictionary<string, string>(); // fieldName → FQN

        foreach (var site in usageSites.Where(s => s.IsAnalyzable || chainMemberIds.Contains(s.UniqueId)))
        {
            // From insert columns
            if (site.InsertInfo != null)
            {
                foreach (var col in site.InsertInfo.Columns)
                {
                    if (col.CustomTypeMappingClass != null)
                        AddIfMissing(mappings, GetMappingFieldName(col.CustomTypeMappingClass), col.CustomTypeMappingClass);
                }
            }

            // From projection columns
            if (site.ProjectionInfo != null)
            {
                foreach (var col in site.ProjectionInfo.Columns)
                {
                    if (col.CustomTypeMapping != null)
                        AddIfMissing(mappings, GetMappingFieldName(col.CustomTypeMapping), col.CustomTypeMapping);
                }
            }

            // From where clause parameters
            if (site.ClauseInfo != null)
            {
                foreach (var p in site.ClauseInfo.Parameters)
                {
                    if (p.CustomTypeMappingClass != null)
                        AddIfMissing(mappings, GetMappingFieldName(p.CustomTypeMappingClass), p.CustomTypeMappingClass);
                }

                // From Set clause mapping
                if (site.ClauseInfo is SetClauseInfo setInfo && setInfo.CustomTypeMappingClass != null)
                    AddIfMissing(mappings, GetMappingFieldName(setInfo.CustomTypeMappingClass), setInfo.CustomTypeMappingClass);
            }
        }

        return mappings;
    }

    /// <summary>
    /// Gets a safe field name for a TypeMapping class instance cache.
    /// E.g. "MyApp.MoneyMapping" → "_mapper_MyApp_MoneyMapping"
    /// </summary>
    private static void AddIfMissing(Dictionary<string, string> dict, string key, string value)
    {
        if (!dict.ContainsKey(key))
            dict[key] = value;
    }

    /// <summary>
    /// Collects all unique EntityReader class FQNs used across all usage sites.
    /// </summary>
    private static Dictionary<string, string> CollectEntityReaderInstances(IReadOnlyList<UsageSiteInfo> usageSites, HashSet<string> chainMemberIds)
    {
        var readers = new Dictionary<string, string>(); // fieldName → FQN

        foreach (var site in usageSites.Where(s => s.IsAnalyzable || chainMemberIds.Contains(s.UniqueId)))
        {
            if (site.ProjectionInfo?.CustomEntityReaderClass != null)
            {
                var fqn = site.ProjectionInfo.CustomEntityReaderClass;
                AddIfMissing(readers, GetEntityReaderFieldName(fqn), fqn);
            }
        }

        return readers;
    }

    /// <summary>
    /// Gets a safe field name for an EntityReader class instance cache.
    /// E.g. "MyApp.UserReader" → "_entityReader_MyApp_UserReader"
    /// </summary>
    internal static string GetEntityReaderFieldName(string readerClassFqn)
    {
        return "_entityReader_" + readerClassFqn.Replace('.', '_').Replace('+', '_');
    }

    internal static string GetMappingFieldName(string mappingClassFqn)
    {
        return "_mapper_" + mappingClassFqn.Replace('.', '_').Replace('+', '_');
    }

    /// <summary>
    /// Wraps a parameter value expression with ToDb() if the parameter has a custom type mapping.
    /// </summary>
    private static string WrapWithToDb(string valueExpr, ParameterInfo param)
    {
        if (param.CustomTypeMappingClass != null)
            return $"{GetMappingFieldName(param.CustomTypeMappingClass)}.ToDb({valueExpr})";
        return valueExpr;
    }

    /// <summary>
    /// Generates the InterceptsLocationAttribute if needed.
    /// Uses new format: InterceptsLocationAttribute(int version, string data)
    /// </summary>
    private static void GenerateInterceptsLocationAttribute(StringBuilder sb)
    {
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
