using System.Text;
using Quarry.Generators.Models;
using Quarry.Generators.Sql;
using Quarry;
using Quarry.Shared.Migration;

namespace Quarry.Generators.Generation;

/// <summary>
/// Generates column metadata source code for query building.
/// </summary>
internal static class MetadataCodeGenerator
{
    /// <summary>
    /// Generates the metadata file for a context.
    /// </summary>
    public static string GenerateMetadata(ContextInfo context)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(context.Namespace))
        {
            sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine();
        }

        // Generate metadata class for each entity
        foreach (var entity in context.Entities)
        {
            GenerateEntityMetadata(sb, entity, context);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates metadata for a single entity.
    /// </summary>
    private static void GenerateEntityMetadata(StringBuilder sb, EntityInfo entity, ContextInfo context)
    {
        var metadataClassName = $"{entity.EntityName}Metadata";

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Column metadata for the {entity.EntityName} entity.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"internal static class {metadataClassName}");
        sb.AppendLine("{");

        // Table name
        sb.AppendLine($"    /// <summary>The database table name.</summary>");
        sb.AppendLine($"    public const string TableName = \"{entity.TableName}\";");
        sb.AppendLine();

        // Qualified table name with schema
        if (!string.IsNullOrEmpty(context.Schema))
        {
            var qualifiedName = FormatQualifiedTableName(context.Schema!, entity.TableName, context.Dialect);
            var escapedName = qualifiedName.Replace("\"", "\\\"");
            sb.AppendLine($"    /// <summary>The fully qualified table name with schema.</summary>");
            sb.AppendLine($"    public const string QualifiedTableName = \"{escapedName}\";");
        }
        else
        {
            var quotedName = QuoteIdentifier(entity.TableName, context.Dialect);
            var escapedName = quotedName.Replace("\"", "\\\"");
            sb.AppendLine($"    /// <summary>The quoted table name.</summary>");
            sb.AppendLine($"    public const string QualifiedTableName = \"{escapedName}\";");
        }
        sb.AppendLine();

        // Column count
        sb.AppendLine($"    /// <summary>The number of columns.</summary>");
        sb.AppendLine($"    public const int ColumnCount = {entity.Columns.Count};");
        sb.AppendLine();

        // Primary key info
        var primaryKey = entity.Columns.FirstOrDefault(c => c.Kind == ColumnKind.PrimaryKey);
        if (primaryKey is not null)
        {
            sb.AppendLine($"    /// <summary>The primary key column name.</summary>");
            sb.AppendLine($"    public const string PrimaryKeyColumn = \"{primaryKey.ColumnName}\";");
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>The primary key property name.</summary>");
            sb.AppendLine($"    public const string PrimaryKeyProperty = \"{primaryKey.PropertyName}\";");
            sb.AppendLine();
        }

        // Composite primary key info
        if (entity.CompositeKeyColumns is { Count: > 0 })
        {
            // Resolve column names from property names
            var ckColumnNames = new List<string>();
            var ckPropertyNames = new List<string>();
            foreach (var propName in entity.CompositeKeyColumns)
            {
                var col = entity.Columns.FirstOrDefault(c => c.PropertyName == propName);
                if (col != null)
                {
                    ckColumnNames.Add(col.ColumnName);
                    ckPropertyNames.Add(col.PropertyName);
                }
            }

            if (ckColumnNames.Count > 0)
            {
                sb.AppendLine($"    /// <summary>The composite primary key column names.</summary>");
                sb.Append($"    public static readonly string[] PrimaryKeyColumns = [");
                sb.Append(string.Join(", ", ckColumnNames.Select(c => $"\"{c}\"")));
                sb.AppendLine("];");
                sb.AppendLine();

                sb.AppendLine($"    /// <summary>The composite primary key property names.</summary>");
                sb.Append($"    public static readonly string[] PrimaryKeyProperties = [");
                sb.Append(string.Join(", ", ckPropertyNames.Select(c => $"\"{c}\"")));
                sb.AppendLine("];");
                sb.AppendLine();
            }
        }

        // Column names array
        sb.AppendLine($"    /// <summary>All column names in order.</summary>");
        sb.Append($"    public static readonly string[] ColumnNames = [");
        sb.Append(string.Join(", ", entity.Columns.Select(c => $"\"{c.ColumnName}\"")));
        sb.AppendLine("];");
        sb.AppendLine();

        // Property names array
        sb.AppendLine($"    /// <summary>All property names in order.</summary>");
        sb.Append($"    public static readonly string[] PropertyNames = [");
        sb.Append(string.Join(", ", entity.Columns.Select(c => $"\"{c.PropertyName}\"")));
        sb.AppendLine("];");
        sb.AppendLine();

        // Column to property mapping
        sb.AppendLine($"    /// <summary>Maps column names to property names.</summary>");
        sb.AppendLine($"    public static readonly Dictionary<string, string> ColumnToProperty = new()");
        sb.AppendLine("    {");
        foreach (var column in entity.Columns)
        {
            sb.AppendLine($"        [\"{column.ColumnName}\"] = \"{column.PropertyName}\",");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // Property to column mapping
        sb.AppendLine($"    /// <summary>Maps property names to column names.</summary>");
        sb.AppendLine($"    public static readonly Dictionary<string, string> PropertyToColumn = new()");
        sb.AppendLine("    {");
        foreach (var column in entity.Columns)
        {
            sb.AppendLine($"        [\"{column.PropertyName}\"] = \"{column.ColumnName}\",");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // Generate individual column metadata
        sb.AppendLine($"    /// <summary>Column metadata.</summary>");
        sb.AppendLine($"    public static class Columns");
        sb.AppendLine("    {");

        foreach (var column in entity.Columns)
        {
            GenerateColumnMetadata(sb, column, context.Dialect, entity.CompositeKeyColumns);
        }

        sb.AppendLine("    }");

        // Generate index metadata
        if (entity.Indexes.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Index metadata.</summary>");
            sb.AppendLine($"    public static class Indexes");
            sb.AppendLine("    {");

            foreach (var index in entity.Indexes)
            {
                GenerateIndexMetadata(sb, index);
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates metadata for a single column.
    /// </summary>
    private static void GenerateColumnMetadata(StringBuilder sb, ColumnInfo column, SqlDialect dialect, IReadOnlyList<string>? compositeKeyColumns = null)
    {
        var quotedColumnName = QuoteIdentifier(column.ColumnName, dialect);
        var escapedQuotedName = quotedColumnName.Replace("\"", "\\\"");

        // A column is a primary key if it's a single Key<T> PK or part of a composite key
        var isPrimaryKey = column.Kind == ColumnKind.PrimaryKey
            || (compositeKeyColumns != null && compositeKeyColumns.Contains(column.PropertyName));

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Metadata for the {column.PropertyName} column.</summary>");
        sb.AppendLine($"        public static class {column.PropertyName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            /// <summary>The database column name.</summary>");
        sb.AppendLine($"            public const string ColumnName = \"{column.ColumnName}\";");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>The quoted column name for SQL.</summary>");
        sb.AppendLine($"            public const string Quoted = \"{escapedQuotedName}\";");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>The CLR type name.</summary>");
        sb.AppendLine($"            public const string ClrType = \"{column.FullClrType}\";");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>Whether the column is nullable.</summary>");
        sb.AppendLine($"            public const bool IsNullable = {(column.IsNullable ? "true" : "false")};");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>Whether this is the primary key.</summary>");
        sb.AppendLine($"            public const bool IsPrimaryKey = {(isPrimaryKey ? "true" : "false")};");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>Whether this is a foreign key.</summary>");
        sb.AppendLine($"            public const bool IsForeignKey = {(column.Kind == ColumnKind.ForeignKey ? "true" : "false")};");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>Whether this is an identity column.</summary>");
        sb.AppendLine($"            public const bool IsIdentity = {(column.Modifiers.IsIdentity ? "true" : "false")};");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>Whether this is a computed column.</summary>");
        sb.AppendLine($"            public const bool IsComputed = {(column.Modifiers.IsComputed ? "true" : "false")};");

        if (column.Modifiers.MaxLength.HasValue)
        {
            sb.AppendLine();
            sb.AppendLine($"            /// <summary>The maximum length.</summary>");
            sb.AppendLine($"            public const int MaxLength = {column.Modifiers.MaxLength.Value};");
        }

        if (column.Modifiers.Precision.HasValue)
        {
            sb.AppendLine();
            sb.AppendLine($"            /// <summary>The numeric precision.</summary>");
            sb.AppendLine($"            public const int Precision = {column.Modifiers.Precision.Value};");
        }

        if (column.Modifiers.Scale.HasValue)
        {
            sb.AppendLine();
            sb.AppendLine($"            /// <summary>The numeric scale.</summary>");
            sb.AppendLine($"            public const int Scale = {column.Modifiers.Scale.Value};");
        }

        if (column.ReferencedEntityName is not null)
        {
            sb.AppendLine();
            sb.AppendLine($"            /// <summary>The referenced entity type name.</summary>");
            sb.AppendLine($"            public const string ReferencedEntity = \"{column.ReferencedEntityName}\";");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Generates metadata for a single index.
    /// </summary>
    private static void GenerateIndexMetadata(StringBuilder sb, IndexInfo index)
    {
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Metadata for the {index.Name} index.</summary>");
        sb.AppendLine($"        public static class {index.Name}");
        sb.AppendLine("        {");
        sb.AppendLine($"            /// <summary>The index name.</summary>");
        sb.AppendLine($"            public const string IndexName = \"{index.Name}\";");
        sb.AppendLine();
        sb.AppendLine($"            /// <summary>Whether this is a unique index.</summary>");
        sb.AppendLine($"            public const bool IsUnique = {(index.IsUnique ? "true" : "false")};");
        sb.AppendLine();

        // Columns
        sb.Append($"            /// <summary>The indexed column names.</summary>");
        sb.AppendLine();
        sb.Append($"            public static readonly string[] Columns = [");
        sb.Append(string.Join(", ", index.Columns.Select(c => $"\"{c.PropertyName}\"")));
        sb.AppendLine("];");
        sb.AppendLine();

        // Sort directions
        sb.Append($"            /// <summary>The sort directions (\"ASC\" or \"DESC\") per column.</summary>");
        sb.AppendLine();
        sb.Append($"            public static readonly string[] Directions = [");
        sb.Append(string.Join(", ", index.Columns.Select(c => c.Direction == SortDirection.Descending ? "\"DESC\"" : "\"ASC\"")));
        sb.AppendLine("];");

        if (index.IndexType != null)
        {
            sb.AppendLine();
            sb.AppendLine($"            /// <summary>The index type.</summary>");
            sb.AppendLine($"            public const string Type = \"{index.IndexType}\";");
        }

        if (index.Filter != null)
        {
            sb.AppendLine();
            sb.AppendLine($"            /// <summary>The filter expression.</summary>");
            sb.AppendLine($"            public const string Filter = \"{index.Filter.Replace("\"", "\\\"")}\";");
            sb.AppendLine();
            sb.AppendLine($"            /// <summary>Whether the filter references a bool column (vs raw SQL).</summary>");
            sb.AppendLine($"            public const bool FilterIsBoolColumn = {(index.FilterIsBoolColumn ? "true" : "false")};");
        }

        if (index.IncludeColumns.Count > 0)
        {
            sb.AppendLine();
            sb.Append($"            /// <summary>Include columns for covering index.</summary>");
            sb.AppendLine();
            sb.Append($"            public static readonly string[] IncludeColumns = [");
            sb.Append(string.Join(", ", index.IncludeColumns.Select(c => $"\"{c}\"")));
            sb.AppendLine("];");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Formats a qualified table name with schema.
    /// </summary>
    private static string FormatQualifiedTableName(string schema, string tableName, SqlDialect dialect)
    {
        var quotedSchema = QuoteIdentifier(schema, dialect);
        var quotedTable = QuoteIdentifier(tableName, dialect);
        return $"{quotedSchema}.{quotedTable}";
    }

    /// <summary>
    /// Quotes an identifier for the specified dialect.
    /// </summary>
    private static string QuoteIdentifier(string identifier, SqlDialect dialect)
    {
        // Escape any embedded quote characters
        var escaped = EscapeIdentifier(identifier, dialect);

        return dialect switch
        {
            SqlDialect.SQLite or SqlDialect.PostgreSQL => $"\"{escaped}\"",
            SqlDialect.MySQL => $"`{escaped}`",
            SqlDialect.SqlServer => $"[{escaped}]",
            _ => $"\"{escaped}\""
        };
    }

    /// <summary>
    /// Escapes special characters in an identifier.
    /// </summary>
    private static string EscapeIdentifier(string identifier, SqlDialect dialect)
    {
        return dialect switch
        {
            SqlDialect.SQLite or SqlDialect.PostgreSQL => identifier.Replace("\"", "\"\""),
            SqlDialect.MySQL => identifier.Replace("`", "``"),
            SqlDialect.SqlServer => identifier.Replace("]", "]]"),
            _ => identifier.Replace("\"", "\"\"")
        };
    }
}
