using System.Collections.Generic;
using System.Linq;
using System.Text;
using Quarry.Generators.Models;
using Quarry.Shared.Migration;

namespace Quarry.Generators.Generation;

/// <summary>
/// Generates the MigrateAsync method on QuarryContext partial classes.
/// </summary>
internal static class MigrateAsyncCodeGenerator
{
    public static string Generate(
        string contextClassName,
        string contextNamespace,
        string dialectName,
        IReadOnlyList<MigrationInfo> migrations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine("using Quarry.Migration;");
        sb.AppendLine();

        // Add usings for migration namespaces
        var namespaces = new HashSet<string>();
        foreach (var m in migrations)
        {
            if (!string.IsNullOrEmpty(m.Namespace))
                namespaces.Add(m.Namespace);
        }
        foreach (var ns in namespaces.OrderBy(n => n))
        {
            sb.Append("using ").Append(ns).AppendLine(";");
        }
        sb.AppendLine();

        sb.Append("namespace ").Append(contextNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("partial class ").AppendLine(contextClassName);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies pending migrations to the database.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public async Task MigrateAsync(DbConnection connection, MigrationOptions? options = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var migrations = new (int Version, string Name, Action<MigrationBuilder> Upgrade, Action<MigrationBuilder> Downgrade, Action<MigrationBuilder> Backup)[]");
        sb.AppendLine("        {");

        var sorted = migrations.OrderBy(m => m.Version).ToList();
        for (var i = 0; i < sorted.Count; i++)
        {
            var m = sorted[i];
            sb.Append("            (").Append(m.Version);
            sb.Append(", \"").Append(CodeGenHelpers.EscapeCSharpString(m.Name)).Append("\"");
            sb.Append(", ").Append(m.ClassName).Append(".Upgrade");
            sb.Append(", ").Append(m.ClassName).Append(".Downgrade");
            sb.Append(", ").Append(m.ClassName).Append(".Backup");
            sb.Append(")");
            if (i < sorted.Count - 1) sb.Append(",");
            sb.AppendLine();
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.Append("        await MigrationRunner.RunAsync(connection, SqlDialect.").Append(dialectName).AppendLine(", migrations, options);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
