using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Quarry.Generators.Generation;
using Quarry.Generators.IR;
using Quarry.Generators.Models;

namespace Quarry.Generators.CodeGen;

/// <summary>
/// Orchestrates per-file interceptor output by routing each site to the
/// appropriate body emitter based on <see cref="InterceptorRouter.Categorize"/>.
/// </summary>
/// <remarks>
/// Output structure per file:
/// <code>
///   // &lt;auto-generated/&gt;
///   #nullable enable
///   using ...;
///   [InterceptsLocation] attribute
///   namespace {contextNamespace} {
///     // Carrier class declarations (file sealed)
///     file static class {Context}.Interceptors.{FileTag} {
///       // Per-site interceptor methods
///     }
///   }
/// </code>
/// </remarks>
internal sealed class FileEmitter
{
    private readonly string _contextClassName;
    private readonly string? _contextNamespace;
    private readonly string _fileTag;
    private readonly IReadOnlyList<TranslatedCallSite> _sites;
    private readonly IReadOnlyList<AssembledPlan>? _chains;
    private readonly IReadOnlyList<CarrierPlan>? _carrierPlans;
    private readonly List<Models.DiagnosticInfo> _emitDiagnostics = new();

    /// <summary>
    /// Diagnostics collected during <see cref="Emit"/>. Populated after Emit() returns.
    /// </summary>
    public IReadOnlyList<Models.DiagnosticInfo> EmitDiagnostics => _emitDiagnostics;

    public FileEmitter(
        string contextClassName,
        string? contextNamespace,
        string fileTag,
        IReadOnlyList<TranslatedCallSite> sites,
        IReadOnlyList<AssembledPlan>? chains = null,
        IReadOnlyList<CarrierPlan>? carrierPlans = null)
    {
        _contextClassName = contextClassName;
        _contextNamespace = contextNamespace;
        _fileTag = fileTag;
        _sites = sites;
        _chains = chains;
        _carrierPlans = carrierPlans;
    }

    /// <summary>
    /// Emits the complete interceptors file for this (context, file) group.
    /// </summary>
    /// <returns>Generated C# source text.</returns>
    public string Emit()
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8602 // Dereference of a possibly null reference.");
        sb.AppendLine();

        // Required usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine("using Quarry.Internal;");
        sb.AppendLine("using Quarry.Logging;");
        sb.AppendLine("using LogLevel = Quarry.Logging.LogLevel;");

        // Collect all unique entity type namespaces
        var entityNamespaces = _sites
            .Select(s => InterceptorCodeGenerator.GetNamespaceFromTypeName(s.EntityTypeName))
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct()
            .ToList();

        // Collect context namespaces
        var contextNamespaces = _sites
            .Select(s => s.ContextNamespace)
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct();

        // Collect entity schema namespaces from prebuilt chains
        var chainSchemaNamespaces = _chains != null
            ? _chains
                .Select(c => c.EntitySchemaNamespace)
                .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
                .Distinct()
            : Enumerable.Empty<string?>();

        var allNamespaces = entityNamespaces
            .Concat(contextNamespaces!)
            .Concat(chainSchemaNamespaces!)
            .Distinct()
            .OrderBy(ns => ns);

        foreach (var ns in allNamespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();

        // InterceptsLocation attribute definition
        InterceptorCodeGenerator.GenerateInterceptsLocationAttribute(sb);
        sb.AppendLine();

        // Namespace
        var interceptorNamespace = !string.IsNullOrEmpty(_contextNamespace)
            ? _contextNamespace
            : "Quarry.Generated";
        sb.AppendLine($"namespace {interceptorNamespace}");
        sb.AppendLine("{");
        sb.AppendLine();

        // Pass 1: Build carrier class infos for carrier-eligible chains and emit at namespace scope
        var carrierLookup = new Dictionary<string, (CarrierPlan Carrier, AssembledPlan Chain)>();
        var carrierClauseLookup = new Dictionary<string, (CarrierPlan Carrier, AssembledPlan Chain)>();
        var carrierFirstClauseIds = new HashSet<string>();
        // Mapping from operand QueryPlan → carrier class name for set operation interceptor emission.
        // Uses reference equality since the same QueryPlan instance is shared between
        // the operand AnalyzedChain and the main chain's SetOperationPlan.Operand.
        var operandCarrierNames = new Dictionary<QueryPlan, string>(QueryPlanReferenceComparer.Instance);
        if (_chains != null && _carrierPlans != null)
        {
            var carrierIndex = 0;
            for (var chainIndex = 0; chainIndex < _chains.Count; chainIndex++)
            {
                var chain = _chains[chainIndex];
                var carrierPlan = chainIndex < _carrierPlans.Count ? _carrierPlans[chainIndex] : null;
                if (carrierPlan == null || !carrierPlan.IsEligible)
                    continue;

                var clauses = chain.GetClauseEntries();
                var hasChainRoot = clauses.Any(c => c.Role == ClauseRole.ChainRoot);
                if (!hasChainRoot && clauses.Count > 0 && clauses[0].IsConditional)
                    continue;

                // Operand chains have no execution terminal — skip the terminal check
                if (!chain.IsOperandChain && !CarrierEmitter.WouldExecutionTerminalBeEmitted(chain))
                    continue;

                // Assign carrier class name and interfaces (deferred from CarrierAnalyzer)
                carrierPlan.ClassName = $"Chain_{carrierIndex}";
                var resolvedInterfaces = CarrierEmitter.ResolveCarrierInterfaceList(chain);
                carrierPlan.BaseClassName = "";
                carrierPlan.ImplementedInterfaces = resolvedInterfaces;
                carrierIndex++;

                if (chain.IsOperandChain)
                {
                    // Operand chains: register carrier name for set operation linking,
                    // but don't register execution site in carrierLookup (no terminal to emit)
                    operandCarrierNames[chain.Plan] = carrierPlan.ClassName;
                }
                else
                {
                    carrierLookup[chain.ExecutionSite.UniqueId] = (carrierPlan, chain);
                    if (chain.PreparedTerminals != null)
                    {
                        foreach (var pt in chain.PreparedTerminals)
                            carrierLookup[pt.UniqueId] = (carrierPlan, chain);
                    }
                    if (chain.PrepareSite != null)
                        carrierLookup[chain.PrepareSite.UniqueId] = (carrierPlan, chain);

                    // CTE inner chains: also register their carrier name keyed by QueryPlan
                    // so EmitCteDefinition can look up the inner carrier class to copy
                    // captured parameters from. CTE inner chains are NOT operand chains
                    // (they retain their own execution terminals for standalone use).
                    // Inspect every clause site rather than relying on a positional invariant —
                    // chain analysis may move ChainRoot away from index 0 in future shapes.
                    var isCteInnerChain = false;
                    foreach (var cs in chain.ClauseSites)
                    {
                        if (cs.Bound.Raw.IsCteInnerChain) { isCteInnerChain = true; break; }
                    }
                    if (isCteInnerChain)
                        operandCarrierNames[chain.Plan] = carrierPlan.ClassName;
                }

                foreach (var clause in clauses)
                {
                    carrierClauseLookup[clause.Site.UniqueId] = (carrierPlan, chain);
                }

                var chainRootClause = clauses
                    .FirstOrDefault(c => c.Role == ClauseRole.ChainRoot);
                if (chainRootClause != null)
                {
                    carrierFirstClauseIds.Add(chainRootClause.Site.UniqueId);
                }
                else if (clauses.Count > 0)
                {
                    carrierFirstClauseIds.Add(clauses[0].Site.UniqueId);
                }

                CarrierEmitter.EmitCarrierClass(sb, carrierPlan, chain, _contextClassName);
            }
        }

        // Resolve compile-time column ordinals for RawSql sites with SQL literals.
        // Sites that resolve successfully get static readers; others fall back to struct readers.
        var rawSqlResolvedColumns = new Dictionary<string, IReadOnlyList<RawSqlColumnResolver.ResolvedColumn>>();
        var rawSqlStructNames = new Dictionary<string, string>();
        {
            int rawSqlStructIndex = 0;
            foreach (var site in _sites)
            {
                if (site.Kind == InterceptorKind.RawSqlAsync
                    && site.RawSqlTypeInfo != null
                    && site.RawSqlTypeInfo.TypeKind != RawSqlTypeKind.Scalar
                    && site.RawSqlTypeInfo.Properties.Count > 0)
                {
                    // Try compile-time column resolution first
                    if (site.RawSqlTypeInfo.SqlLiteral != null)
                    {
                        var resolution = RawSqlColumnResolver.Resolve(
                            site.RawSqlTypeInfo.SqlLiteral,
                            site.Dialect,
                            site.RawSqlTypeInfo.Properties);

                        if (resolution.IsResolved)
                        {
                            rawSqlResolvedColumns[site.UniqueId] = resolution.Columns!;
                            continue; // Skip struct creation — static reader will be used
                        }

                        // Resolution failed — collect diagnostic if applicable
                        if (resolution.UnresolvableColumnPosition >= 0)
                        {
                            _emitDiagnostics.Add(new Models.DiagnosticInfo(
                                "QRY041",
                                site.Location,
                                resolution.UnresolvableColumnPosition.ToString()));
                        }
                    }

                    // Fall back to struct-based reader
                    var structName = $"RawSqlReader_{site.RawSqlTypeInfo.ResultTypeName}_{rawSqlStructIndex}";
                    rawSqlStructNames[site.UniqueId] = structName;
                    RawSqlBodyEmitter.EmitRowReaderStruct(sb, site.RawSqlTypeInfo, structName);
                    rawSqlStructIndex++;
                }
            }
        }

        // File-scoped interceptor class
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated interceptors for {_contextClassName} query methods.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"file static class {_contextClassName}Interceptors_{_fileTag}");
        sb.AppendLine("{");

        // Build chain analysis lookups for execution interceptor generation
        var chainLookup = new Dictionary<string, AssembledPlan>();
        var clauseBitMap = new Dictionary<string, int>();
        var chainMemberIds = new HashSet<string>();
        if (_chains != null)
        {
            foreach (var chain in _chains)
            {
                // Operand chains have no execution terminal — don't register in chainLookup.
                // Their ChainRoot is already in clauseSites and handled via carrierClauseLookup.
                if (!chain.IsOperandChain)
                {
                    chainLookup[chain.ExecutionSite.UniqueId] = chain;
                    chainMemberIds.Add(chain.ExecutionSite.UniqueId);
                }

                // Register prepared terminals and .Prepare() site in chain lookup
                if (chain.PreparedTerminals != null)
                {
                    foreach (var pt in chain.PreparedTerminals)
                    {
                        chainLookup[pt.UniqueId] = chain;
                        chainMemberIds.Add(pt.UniqueId);
                    }
                }
                if (chain.PrepareSite != null)
                {
                    chainLookup[chain.PrepareSite.UniqueId] = chain;
                    chainMemberIds.Add(chain.PrepareSite.UniqueId);
                }
                foreach (var clause in chain.GetClauseEntries())
                {
                    chainMemberIds.Add(clause.Site.UniqueId);
                    if (clause.IsConditional && clause.BitIndex.HasValue)
                    {
                        clauseBitMap[clause.Site.UniqueId] = clause.BitIndex.Value;
                    }
                }
            }
        }

        // Build clause → chain lookup
        var chainClauseLookup = new Dictionary<string, AssembledPlan>();
        var firstClauseIds = new HashSet<string>();
        if (_chains != null)
        {
            foreach (var chain in _chains)
            {
                var clauses = chain.GetClauseEntries();
                foreach (var clause in clauses)
                {
                    chainClauseLookup[clause.Site.UniqueId] = chain;
                }
                if (clauses.Count > 0)
                {
                    var firstClause = clauses[0];
                    firstClauseIds.Add(firstClause.Site.UniqueId);
                    if (firstClause.Role == ClauseRole.ChainRoot
                        && !carrierClauseLookup.ContainsKey(firstClause.Site.UniqueId)
                        && clauses.Count > 1)
                    {
                        firstClauseIds.Add(clauses[1].Site.UniqueId);
                    }
                }
            }
        }

        // Collect all static fields needed for cached extractors
        var carrierMemberIds = new HashSet<string>(carrierClauseLookup.Keys);
        var staticFields = InterceptorCodeGenerator.CollectStaticFields(_sites, chainMemberIds);

        // Collect all unique TypeMapping classes
        var mappingInstances = InterceptorCodeGenerator.CollectMappingInstances(_sites, chainMemberIds);

        // Collect all unique EntityReader classes
        var entityReaderInstances = InterceptorCodeGenerator.CollectEntityReaderInstances(_sites, chainMemberIds, _chains);

        if (mappingInstances.Count > 0 || entityReaderInstances.Count > 0)
        {
            sb.AppendLine("    #region Cached Fields");
            sb.AppendLine();
            foreach (var mapping in mappingInstances)
            {
                sb.AppendLine($"    private static readonly {mapping.Value} {mapping.Key} = new();");
            }
            foreach (var reader in entityReaderInstances)
            {
                sb.AppendLine($"    private static readonly {reader.Value} {reader.Key} = new();");
            }
            sb.AppendLine();
            sb.AppendLine("    #endregion");
            sb.AppendLine();
        }

        // Build the filtered list of sites for generation
        var allSitesForGeneration = _sites
            .Where(s => s.IsAnalyzable || chainMemberIds.Contains(s.UniqueId))
            .ToList();

        // Group interceptors by chain
        var processedSiteIds = new HashSet<string>();
        var chainGroups = new List<(string Label, List<TranslatedCallSite> Sites, IReadOnlyList<string>? TraceLines)>();
        var siteByUniqueId = allSitesForGeneration.ToDictionary(s => s.UniqueId);

        if (_chains != null)
        {
            foreach (var chain in _chains)
            {
                var chainSites = new List<TranslatedCallSite>();
                foreach (var clause in chain.GetClauseEntries())
                {
                    // PipelineOrchestrator has already propagated chain-updated sites
                    // (e.g., JoinedEntityTypeNames) back into the main site array,
                    // so we can use the sites from allSitesForGeneration directly.
                    var useSite = siteByUniqueId.TryGetValue(clause.Site.UniqueId, out var resolved)
                        ? resolved : clause.Site;
                    chainSites.Add(useSite);
                    processedSiteIds.Add(useSite.UniqueId);
                }

                // Operand chains: executionSite is the ChainRoot (already in clauseSites).
                // Don't add it again to avoid duplicate interceptor generation.
                if (!chain.IsOperandChain)
                {
                    var chainExecSite = siteByUniqueId.TryGetValue(chain.ExecutionSite.UniqueId, out var resolvedExec)
                        ? resolvedExec : chain.ExecutionSite;
                    chainSites.Add(chainExecSite);
                    processedSiteIds.Add(chainExecSite.UniqueId);
                }

                if (chainSites.Count > 0)
                {
                    var execMethod = chain.ExecutionSite.MethodName;
                    var label = chain.IsOperandChain
                        ? $"Operand: {execMethod} at line {chain.ExecutionSite.Line}"
                        : $"Chain: {execMethod} at line {chain.ExecutionSite.Line}";
                    chainGroups.Add((label, chainSites, chain.TraceLines));
                }
            }
        }

        // Remaining sites not part of any chain
        var standaloneSites = allSitesForGeneration
            .Where(s => !processedSiteIds.Contains(s.UniqueId))
            .ToList();

        if (standaloneSites.Count > 0)
        {
            chainGroups.Add(("Standalone Interceptors", standaloneSites, null));
        }

        // Pre-group static fields by method name
        var staticFieldsByMethod = new Dictionary<string, List<InterceptorCodeGenerator.CachedExtractorField>>();
        foreach (var f in staticFields)
        {
            if (!staticFieldsByMethod.TryGetValue(f.MethodName, out var list))
            {
                list = new List<InterceptorCodeGenerator.CachedExtractorField>();
                staticFieldsByMethod[f.MethodName] = list;
            }
            list.Add(f);
        }

        // Generate grouped output
        foreach (var (label, sites, traceLines) in chainGroups)
        {
            sb.AppendLine($"    #region {label}");
            sb.AppendLine();

            // Emit trace comments inside the region for traced chains
            if (traceLines != null)
            {
                foreach (var line in traceLines)
                    sb.AppendLine($"    // {line}");
                sb.AppendLine();
            }
            foreach (var site in sites)
            {
                EmitInterceptorMethod(sb, site, staticFields, staticFieldsByMethod, chainLookup, clauseBitMap, chainClauseLookup, firstClauseIds, carrierLookup, carrierClauseLookup, carrierFirstClauseIds, rawSqlStructNames, rawSqlResolvedColumns, operandCarrierNames);
            }
            sb.AppendLine($"    #endregion");
            sb.AppendLine();
        }

        sb.AppendLine("}"); // Close interceptor class
        sb.AppendLine("}"); // Close namespace

        return sb.ToString();
    }

    /// <summary>
    /// Generates an interceptor method for a usage site.
    /// Handles skip checks, XML docs, [InterceptsLocation] attribute, and dispatches
    /// to the appropriate body emitter.
    /// </summary>
    private static void EmitInterceptorMethod(
        StringBuilder sb,
        TranslatedCallSite site,
        List<InterceptorCodeGenerator.CachedExtractorField> staticFields,
        Dictionary<string, List<InterceptorCodeGenerator.CachedExtractorField>> staticFieldsByMethod,
        Dictionary<string, AssembledPlan> chainLookup,
        Dictionary<string, int> clauseBitMap,
        Dictionary<string, AssembledPlan> chainClauseLookup,
        HashSet<string> firstClauseIds,
        Dictionary<string, (CarrierPlan Carrier, AssembledPlan Chain)>? carrierLookup = null,
        Dictionary<string, (CarrierPlan Carrier, AssembledPlan Chain)>? carrierClauseLookup = null,
        HashSet<string>? carrierFirstClauseIds = null,
        Dictionary<string, string>? rawSqlStructNames = null,
        Dictionary<string, IReadOnlyList<RawSqlColumnResolver.ResolvedColumn>>? rawSqlResolvedColumns = null,
        Dictionary<QueryPlan, string>? operandCarrierNames = null)
    {
        // Trace sites are compile-time-only signals — no interceptor generated
        if (site.Kind == InterceptorKind.Trace)
            return;

        // Check if this site belongs to a carrier-optimized chain
        var isCarrierSite = false;
        CarrierPlan? carrierInfo = null;
        AssembledPlan? carrierChain = null;

        if (carrierLookup != null && carrierLookup.TryGetValue(site.UniqueId, out var carrierExec))
        {
            isCarrierSite = true;
            carrierInfo = carrierExec.Carrier;
            carrierChain = carrierExec.Chain;
        }
        else if (carrierClauseLookup != null && carrierClauseLookup.TryGetValue(site.UniqueId, out var carrierClause))
        {
            isCarrierSite = true;
            carrierInfo = carrierClause.Carrier;
            carrierChain = carrierClause.Chain;
        }

        // Carrier-only architecture: skip all non-carrier sites except RawSql
        if (!isCarrierSite)
        {
            if (site.Kind is not (InterceptorKind.RawSqlAsync or InterceptorKind.RawSqlScalarAsync))
                return;
        }

        // Execution interceptor validation
        if (site.Kind is InterceptorKind.ExecuteFetchAll or InterceptorKind.ExecuteFetchFirst
            or InterceptorKind.ExecuteFetchFirstOrDefault or InterceptorKind.ExecuteFetchSingle
            or InterceptorKind.ExecuteFetchSingleOrDefault or InterceptorKind.ToAsyncEnumerable)
        {
            if (!chainLookup.TryGetValue(site.UniqueId, out var chain))
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} Method={site.MethodName} — NOT in chainLookup (chainLookup has {chainLookup.Count} entries)");
                return;
            }
            if (chain.UnmatchedMethodNames != null)
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — UnmatchedMethodNames={string.Join(",", chain.UnmatchedMethodNames)}");
                return;
            }
            var rawResult = InterceptorCodeGenerator.ResolveExecutionResultType(site.ResultTypeName, chain.ResultTypeName, chain.ProjectionInfo);
            if (string.IsNullOrEmpty(rawResult))
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — empty result type. site.ResultTypeName={site.ResultTypeName ?? "(null)"} chain.ResultTypeName={chain.ResultTypeName ?? "(null)"} projInfo={chain.ProjectionInfo?.ResultTypeName ?? "(null)"}");
                return;
            }
            if (chain.ReaderDelegateCode == null)
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — ReaderDelegateCode is null. QueryKind={chain.QueryKind} ProjInfo={chain.ProjectionInfo != null} ProjCols={chain.ProjectionInfo?.Columns.Count ?? 0}");
                return;
            }
            if (chain.ProjectionInfo != null)
            {
                var hasAmbiguousColumns = chain.ProjectionInfo.Columns.Any(c =>
                    c.SqlExpression != null && !string.IsNullOrEmpty(c.ColumnName));
                if (hasAmbiguousColumns)
                {
                    sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — ambiguous columns. ProjKind={chain.ProjectionInfo.Kind}");
                    foreach (var col in chain.ProjectionInfo.Columns)
                        sb.AppendLine($"    //   Col: Name={col.PropertyName ?? "(null)"} ColumnName={col.ColumnName ?? "(null)"} SqlExpr={col.SqlExpression ?? "(null)"} ClrType={col.ClrType ?? "(null)"}");
                    return;
                }
            }
        }
        else if (site.Kind is InterceptorKind.ExecuteScalar)
        {
            if (!chainLookup.TryGetValue(site.UniqueId, out var scalarChain))
            {
                sb.AppendLine($"    // TRACE SKIPPED SCALAR: Kind={site.Kind} UniqueId={site.UniqueId} — NOT in chainLookup");
                return;
            }
            if (scalarChain.UnmatchedMethodNames != null)
                return;
            var rawScalarResult = InterceptorCodeGenerator.ResolveExecutionResultType(site.ResultTypeName, scalarChain.ResultTypeName, scalarChain.ProjectionInfo);
            if (string.IsNullOrEmpty(rawScalarResult))
                return;
        }
        else if (site.Kind is InterceptorKind.ExecuteNonQuery)
        {
            if (!chainLookup.TryGetValue(site.UniqueId, out var nqChain))
            {
                sb.AppendLine($"    // TRACE SKIPPED NONQUERY: Kind={site.Kind} UniqueId={site.UniqueId} — NOT in chainLookup");
                return;
            }
            if (nqChain.SqlVariants.Values.Any(v => string.IsNullOrWhiteSpace(v.Sql)
                || (nqChain.QueryKind == QueryKind.Update && v.Sql.Contains("SET  "))))
                return;
        }
        else if (site.Kind is InterceptorKind.ToDiagnostics)
        {
            if (chainLookup.TryGetValue(site.UniqueId, out var diagChain)
                && diagChain.UnmatchedMethodNames != null)
                return;
            if (!chainLookup.ContainsKey(site.UniqueId) && site.ResultTypeName != null)
                return;
        }

        var methodName = $"{site.MethodName}_{site.UniqueId}";

        // Determine chain analysis status for remarks
        AssembledPlan? chainForRemarks = null;
        chainLookup.TryGetValue(site.UniqueId, out chainForRemarks);
        if (chainForRemarks == null)
            chainClauseLookup.TryGetValue(site.UniqueId, out chainForRemarks);

        // XML documentation
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Intercepts {site.MethodName}() call at {InterceptorCodeGenerator.GetRelativePath(site.FilePath)}:{site.Line}:{site.Column}");
        sb.AppendLine($"    /// </summary>");
        if (chainForRemarks != null)
        {
            sb.AppendLine($"    /// <remarks>Chain: PrebuiltDispatch ({chainForRemarks.Plan.PossibleMasks.Count} variants)</remarks>");
        }
        else
            sb.AppendLine($"    /// <remarks>Chain: Not Analyzed (standalone interceptor)</remarks>");

        // InterceptsLocation attribute
        if (!string.IsNullOrEmpty(site.InterceptableLocationData))
        {
            sb.AppendLine($"    [InterceptsLocation({site.InterceptableLocationVersion}, \"{site.InterceptableLocationData}\")]");
        }
        else
        {
            sb.AppendLine($"    // WARNING: Could not generate InterceptsLocation for this call site");
            return;
        }

        // Check if this is on a joined builder type
        var isJoinedBuilder = site.JoinedEntityTypeNames != null && site.JoinedEntityTypeNames.Count >= 2;

        // Look up clause bitmask bit index
        int? clauseBit = clauseBitMap.TryGetValue(site.UniqueId, out var rawBit) ? rawBit : null;

        // Resolve prebuilt chain membership for clause sites
        chainClauseLookup.TryGetValue(site.UniqueId, out var prebuiltClauseChain);
        var isFirstClauseInChain = prebuiltClauseChain != null && firstClauseIds.Contains(site.UniqueId);

        // For carrier chains, override isFirstInChain
        if (isCarrierSite && carrierFirstClauseIds != null)
        {
            isFirstClauseInChain = carrierFirstClauseIds.Contains(site.UniqueId);
        }

        // Dispatch to body emitters
        switch (site.Kind)
        {
            case InterceptorKind.Select:
                if (isJoinedBuilder)
                    JoinBodyEmitter.EmitJoinedSelect(sb, site, methodName, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                else
                    ClauseBodyEmitter.EmitSelect(sb, site, methodName, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.Where:
                {
                    staticFieldsByMethod.TryGetValue(methodName, out var methodFields);
                    if (isJoinedBuilder)
                        JoinBodyEmitter.EmitJoinedWhere(sb, site, methodName, methodFields, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                    else
                        ClauseBodyEmitter.EmitWhere(sb, site, methodName, methodFields, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                }
                break;

            case InterceptorKind.OrderBy:
            case InterceptorKind.ThenBy:
                if (isJoinedBuilder)
                    JoinBodyEmitter.EmitJoinedOrderBy(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                else
                    ClauseBodyEmitter.EmitOrderBy(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.GroupBy:
                ClauseBodyEmitter.EmitGroupBy(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.Having:
                ClauseBodyEmitter.EmitHaving(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.Set:
                ClauseBodyEmitter.EmitSet(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.Join:
            case InterceptorKind.LeftJoin:
            case InterceptorKind.RightJoin:
            case InterceptorKind.CrossJoin:
            case InterceptorKind.FullOuterJoin:
                JoinBodyEmitter.EmitJoin(sb, site, methodName, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.ExecuteFetchAll:
            case InterceptorKind.ExecuteFetchFirst:
            case InterceptorKind.ExecuteFetchFirstOrDefault:
            case InterceptorKind.ExecuteFetchSingle:
            case InterceptorKind.ExecuteFetchSingleOrDefault:
            case InterceptorKind.ExecuteScalar:
            case InterceptorKind.ToAsyncEnumerable:
                if (chainLookup.TryGetValue(site.UniqueId, out var selectChain))
                {
                    if (selectChain.IsJoinChain)
                        TerminalBodyEmitter.EmitJoinReaderTerminal(sb, site, methodName, selectChain, carrierInfo!);
                    else
                        TerminalBodyEmitter.EmitReaderTerminal(sb, site, methodName, selectChain, carrierInfo!);
                }
                break;

            case InterceptorKind.ExecuteNonQuery:
                if (chainLookup.TryGetValue(site.UniqueId, out var nonQueryChain))
                {
                    if (nonQueryChain.QueryKind == QueryKind.BatchInsert)
                        TerminalBodyEmitter.EmitBatchInsertNonQueryTerminal(sb, site, methodName, nonQueryChain, carrierInfo!);
                    else if (nonQueryChain.QueryKind == QueryKind.Insert)
                        TerminalBodyEmitter.EmitInsertNonQueryTerminal(sb, site, methodName, nonQueryChain, carrierInfo!);
                    else
                        TerminalBodyEmitter.EmitNonQueryTerminal(sb, site, methodName, nonQueryChain, carrierInfo!);
                }
                break;

            case InterceptorKind.ToDiagnostics:
                if (chainLookup.TryGetValue(site.UniqueId, out var toDiagChain))
                {
                    if (toDiagChain.QueryKind == QueryKind.BatchInsert)
                        TerminalBodyEmitter.EmitBatchInsertDiagnosticsTerminal(sb, site, methodName, toDiagChain, carrierInfo!);
                    else
                        TerminalBodyEmitter.EmitDiagnosticsTerminal(sb, site, methodName, toDiagChain, carrierInfo!);
                }
                break;

            case InterceptorKind.DeleteWhere:
                {
                    staticFieldsByMethod.TryGetValue(methodName, out var deleteMethodFields);
                    ClauseBodyEmitter.EmitModificationWhere(sb, site, methodName, deleteMethodFields, isDelete: true, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                }
                break;

            case InterceptorKind.UpdateSet:
                ClauseBodyEmitter.EmitUpdateSet(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.UpdateSetAction:
                ClauseBodyEmitter.EmitUpdateSetAction(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.UpdateSetPoco:
                ClauseBodyEmitter.EmitUpdateSetPoco(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.UpdateWhere:
                {
                    staticFieldsByMethod.TryGetValue(methodName, out var updateMethodFields);
                    ClauseBodyEmitter.EmitModificationWhere(sb, site, methodName, updateMethodFields, isDelete: false, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                }
                break;

            case InterceptorKind.InsertExecuteNonQuery:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var insertChain);
                    TerminalBodyEmitter.EmitInsertNonQueryTerminal(sb, site, methodName, insertChain, carrierInfo!);
                }
                break;

            case InterceptorKind.InsertExecuteScalar:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var insertScalarChain);
                    TerminalBodyEmitter.EmitInsertScalarTerminal(sb, site, methodName, insertScalarChain, carrierInfo!);
                }
                break;

            case InterceptorKind.InsertToDiagnostics:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var insertDiagChain);
                    TerminalBodyEmitter.EmitInsertDiagnosticsTerminal(sb, site, methodName, insertDiagChain, carrierInfo!);
                }
                break;

            case InterceptorKind.RawSqlAsync:
                {
                    IReadOnlyList<RawSqlColumnResolver.ResolvedColumn>? resolvedCols = null;
                    rawSqlResolvedColumns?.TryGetValue(site.UniqueId, out resolvedCols);
                    string? structName = null;
                    rawSqlStructNames?.TryGetValue(site.UniqueId, out structName);
                    RawSqlBodyEmitter.EmitRawSqlAsync(sb, site, methodName, structName, resolvedCols);
                }
                break;

            case InterceptorKind.RawSqlScalarAsync:
                RawSqlBodyEmitter.EmitRawSqlScalarAsync(sb, site, methodName);
                break;

            case InterceptorKind.Limit:
            case InterceptorKind.Offset:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitPagination(sb, site, methodName, carrierInfo, carrierChain);
                break;

            case InterceptorKind.Distinct:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitDistinct(sb, site, methodName, carrierInfo, carrierChain);
                break;

            case InterceptorKind.WithTimeout:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitWithTimeout(sb, site, methodName, carrierInfo, carrierChain);
                break;

            case InterceptorKind.ChainRoot:
                if (carrierInfo != null && carrierChain != null)
                {
                    // When a ChainRoot follows a CteDefinition in the same chain
                    // (e.g., db.With<A>(inner).Users()), the carrier was already created
                    // by the CteDefinition emitter. Cast instead of allocating a new carrier.
                    bool chainHasCte = false;
                    foreach (var cs in carrierChain.ClauseSites)
                    {
                        if (cs.Kind == InterceptorKind.CteDefinition) { chainHasCte = true; break; }
                    }
                    if (chainHasCte)
                        TransitionBodyEmitter.EmitChainRootAfterCte(sb, site, methodName);
                    else
                        TransitionBodyEmitter.EmitChainRoot(sb, site, methodName, carrierInfo);
                }
                break;

            case InterceptorKind.CteDefinition:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitCteDefinition(sb, site, methodName, carrierInfo, carrierChain, operandCarrierNames);
                break;

            case InterceptorKind.FromCte:
                if (carrierInfo != null)
                    TransitionBodyEmitter.EmitFromCte(sb, site, methodName, carrierInfo);
                break;

            case InterceptorKind.DeleteTransition:
            case InterceptorKind.UpdateTransition:
                if (carrierInfo != null)
                    TransitionBodyEmitter.EmitDeleteUpdateTransition(sb, site, methodName);
                break;

            case InterceptorKind.InsertTransition:
                if (carrierInfo != null)
                    TransitionBodyEmitter.EmitInsertTransition(sb, site, methodName, carrierInfo);
                break;

            case InterceptorKind.BatchInsertColumnSelector:
                if (carrierInfo != null)
                    TransitionBodyEmitter.EmitBatchInsertColumnSelector(sb, site, methodName, carrierInfo);
                break;

            case InterceptorKind.BatchInsertValues:
                if (carrierInfo != null)
                    TransitionBodyEmitter.EmitBatchInsertValues(sb, site, methodName, carrierInfo);
                break;

            case InterceptorKind.BatchInsertExecuteNonQuery:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var batchInsertChain);
                    TerminalBodyEmitter.EmitBatchInsertNonQueryTerminal(sb, site, methodName, batchInsertChain, carrierInfo!);
                }
                break;

            case InterceptorKind.BatchInsertExecuteScalar:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var batchInsertScalarChain);
                    TerminalBodyEmitter.EmitBatchInsertScalarTerminal(sb, site, methodName, batchInsertScalarChain, carrierInfo!);
                }
                break;

            case InterceptorKind.BatchInsertToDiagnostics:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var batchInsertDiagChain);
                    TerminalBodyEmitter.EmitBatchInsertDiagnosticsTerminal(sb, site, methodName, batchInsertDiagChain, carrierInfo!);
                }
                break;

            case InterceptorKind.AllTransition:
                TransitionBodyEmitter.EmitAllTransition(sb, site, methodName, carrierInfo);
                break;

            case InterceptorKind.Prepare:
                {
                    // Prepare interceptor: cast builder to PreparedQuery<TResult> (zero-overhead for single-terminal collapse)
                    chainLookup.TryGetValue(site.UniqueId, out var prepareChain);
                    TerminalBodyEmitter.EmitPrepareInterceptor(sb, site, methodName, prepareChain, carrierInfo);
                }
                break;

            case InterceptorKind.Union:
            case InterceptorKind.UnionAll:
            case InterceptorKind.Intersect:
            case InterceptorKind.IntersectAll:
            case InterceptorKind.Except:
            case InterceptorKind.ExceptAll:
                if (carrierInfo != null && carrierChain != null)
                {
                    // Compute which set operation index this site corresponds to by counting
                    // how many set operation sites precede this one in the chain's clause entries.
                    var setOpIndex = 0;
                    foreach (var clause in carrierChain.GetClauseEntries())
                    {
                        if (clause.Site.UniqueId == site.UniqueId) break;
                        if (clause.Role == ClauseRole.SetOperation) setOpIndex++;
                    }
                    SetOperationBodyEmitter.EmitSetOperation(sb, site, methodName, carrierInfo, carrierChain, setOpIndex, operandCarrierNames);
                }
                break;

            default:
                InterceptorCodeGenerator.GeneratePlaceholderInterceptor(sb, site, methodName);
                break;
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Reference-equality comparer for QueryPlan keys (netstandard2.0 compatible).
    /// </summary>
    private sealed class QueryPlanReferenceComparer : IEqualityComparer<QueryPlan>
    {
        public static readonly QueryPlanReferenceComparer Instance = new();
        public bool Equals(QueryPlan x, QueryPlan y) => ReferenceEquals(x, y);
        public int GetHashCode(QueryPlan obj) => System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(obj);
    }

    /// <summary>
    /// Structural key for carrier class deduplication. Two carriers with the same key
    /// produce identical class text (modulo class name) and can share a single definition.
    /// </summary>
    private readonly struct CarrierStructuralKey : IEquatable<CarrierStructuralKey>
    {
        private readonly IReadOnlyList<CarrierField> _fields;
        private readonly string? _maskType;
        private readonly int _maskBitCount;
        private readonly IReadOnlyList<CapturedVariableExtractor> _extractors;
        private readonly Dictionary<int, AssembledSqlVariant> _sqlVariants;
        private readonly string? _readerDelegateCode;
        private readonly bool _hasCollectionParam;
        private readonly string[] _interfaces;
        private readonly int _hashCode;

        private CarrierStructuralKey(
            IReadOnlyList<CarrierField> fields,
            string? maskType,
            int maskBitCount,
            IReadOnlyList<CapturedVariableExtractor> extractors,
            Dictionary<int, AssembledSqlVariant> sqlVariants,
            string? readerDelegateCode,
            bool hasCollectionParam,
            string[] interfaces)
        {
            _fields = fields;
            _maskType = maskType;
            _maskBitCount = maskBitCount;
            _extractors = extractors;
            _sqlVariants = sqlVariants;
            _readerDelegateCode = readerDelegateCode;
            _hasCollectionParam = hasCollectionParam;
            _interfaces = interfaces;

            var hash = new HashCode();
            hash.Add(fields.Count);
            hash.Add(maskType);
            hash.Add(maskBitCount);
            hash.Add(extractors.Count);
            hash.Add(sqlVariants.Count);
            hash.Add(readerDelegateCode);
            hash.Add(hasCollectionParam);
            hash.Add(interfaces.Length);
            foreach (var kvp in sqlVariants)
            {
                hash.Add(kvp.Key);
                hash.Add(kvp.Value.Sql);
                break;
            }
            _hashCode = hash.ToHashCode();
        }

        public static CarrierStructuralKey Create(
            CarrierPlan carrier, AssembledPlan chain, string[] resolvedInterfaces)
        {
            var extractors = new List<CapturedVariableExtractor>();
            foreach (var plan in carrier.ExtractionPlans)
            {
                foreach (var ext in plan.Extractors)
                    extractors.Add(ext);
            }

            var readerCode = chain.ReaderDelegateCode != null && CarrierEmitter.IsReaderSelfContained(chain)
                ? chain.ReaderDelegateCode
                : null;

            var hasCollection = false;
            foreach (var p in chain.ChainParameters)
            {
                if (p.IsCollection) { hasCollection = true; break; }
            }

            return new CarrierStructuralKey(
                carrier.Fields,
                carrier.MaskType,
                carrier.MaskBitCount,
                extractors,
                chain.SqlVariants,
                readerCode,
                hasCollection,
                resolvedInterfaces);
        }

        public bool Equals(CarrierStructuralKey other)
        {
            if (_hashCode != other._hashCode) return false;
            if (_maskType != other._maskType) return false;
            if (_maskBitCount != other._maskBitCount) return false;
            if (_hasCollectionParam != other._hasCollectionParam) return false;
            if (_readerDelegateCode != other._readerDelegateCode) return false;
            if (!EqualityHelpers.SequenceEqual(_fields, other._fields)) return false;
            if (!EqualityHelpers.SequenceEqual(_extractors, other._extractors)) return false;
            if (!EqualityHelpers.DictionaryEqual(_sqlVariants, other._sqlVariants)) return false;
            if (_interfaces.Length != other._interfaces.Length) return false;
            for (int i = 0; i < _interfaces.Length; i++)
            {
                if (_interfaces[i] != other._interfaces[i]) return false;
            }
            return true;
        }

        public override bool Equals(object? obj) => obj is CarrierStructuralKey other && Equals(other);
        public override int GetHashCode() => _hashCode;
    }
}
