using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Quarry.Generators.Generation;
using Quarry.Generators.Models;

namespace Quarry.Generators.CodeGen;

/// <summary>
/// Orchestrates per-file interceptor output by routing each site to the
/// appropriate body emitter based on <see cref="InterceptorRouter.Categorize"/>.
/// </summary>
/// <remarks>
/// Output structure per file:
/// <code>
///   // &lt;auto-generated/&gt;
///   #nullable enable
///   using ...;
///   [InterceptsLocation] attribute
///   namespace {contextNamespace} {
///     // Carrier class declarations (file sealed)
///     file static class {Context}.Interceptors.{FileTag} {
///       // Per-site interceptor methods
///     }
///   }
/// </code>
/// </remarks>
internal sealed class FileEmitter
{
    private readonly string _contextClassName;
    private readonly string? _contextNamespace;
    private readonly string _fileTag;
    private readonly IReadOnlyList<UsageSiteInfo> _sites;
    private readonly IReadOnlyList<PrebuiltChainInfo>? _chains;

    public FileEmitter(
        string contextClassName,
        string? contextNamespace,
        string fileTag,
        IReadOnlyList<UsageSiteInfo> sites,
        IReadOnlyList<PrebuiltChainInfo>? chains = null)
    {
        _contextClassName = contextClassName;
        _contextNamespace = contextNamespace;
        _fileTag = fileTag;
        _sites = sites;
        _chains = chains;
    }

    /// <summary>
    /// Emits the complete interceptors file for this (context, file) group.
    /// </summary>
    /// <returns>Generated C# source text.</returns>
    public string Emit()
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8602 // Dereference of a possibly null reference.");
        sb.AppendLine();

        // Required usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Quarry;");
        sb.AppendLine("using Quarry.Internal;");
        sb.AppendLine("using Quarry.Logging;");
        sb.AppendLine("using Logsmith;");

        // Collect all unique entity type namespaces
        var entityNamespaces = _sites
            .Select(s => InterceptorCodeGenerator.GetNamespaceFromTypeName(s.EntityTypeName))
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct()
            .ToList();

        // Also collect namespaces from the source file of each usage site
        var fileNamespaces = _sites
            .Select(s => InterceptorCodeGenerator.GetNamespaceFromFilePath(s.InvocationSyntax))
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct();

        // Collect context namespaces
        var contextNamespaces = _sites
            .Select(s => s.ContextNamespace)
            .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
            .Distinct();

        // Collect entity schema namespaces from prebuilt chains
        var chainSchemaNamespaces = _chains != null
            ? _chains
                .Select(c => c.EntitySchemaNamespace)
                .Where(ns => !string.IsNullOrEmpty(ns) && ns != "Quarry" && ns != "System")
                .Distinct()
            : Enumerable.Empty<string?>();

        var allNamespaces = entityNamespaces
            .Concat(fileNamespaces)
            .Concat(contextNamespaces!)
            .Concat(chainSchemaNamespaces!)
            .Distinct()
            .OrderBy(ns => ns);

        foreach (var ns in allNamespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();

        // InterceptsLocation attribute definition
        InterceptorCodeGenerator.GenerateInterceptsLocationAttribute(sb);
        sb.AppendLine();

        // Namespace
        var interceptorNamespace = !string.IsNullOrEmpty(_contextNamespace)
            ? _contextNamespace
            : "Quarry.Generated";
        sb.AppendLine($"namespace {interceptorNamespace}");
        sb.AppendLine("{");
        sb.AppendLine();

        // Pass 1: Build carrier class infos for carrier-eligible chains and emit at namespace scope
        var carrierLookup = new Dictionary<string, (CarrierClassInfo Carrier, PrebuiltChainInfo Chain)>();
        var carrierClauseLookup = new Dictionary<string, (CarrierClassInfo Carrier, PrebuiltChainInfo Chain)>();
        var carrierFirstClauseIds = new HashSet<string>();
        if (_chains != null)
        {
            var carrierIndex = 0;
            foreach (var chain in _chains)
            {
                if (!chain.IsCarrierEligible)
                    continue;

                var hasChainRoot = chain.Analysis.Clauses.Any(c => c.Role == ClauseRole.ChainRoot);
                if (!hasChainRoot && chain.Analysis.Clauses.Count > 0 && chain.Analysis.Clauses[0].IsConditional)
                    continue;

                if (!CarrierEmitter.WouldExecutionTerminalBeEmitted(chain))
                    continue;

                var resolvedBase = CarrierEmitter.ResolveCarrierBaseClass(chain);
                var carrier = CarrierClassBuilder.Build(chain, carrierIndex, resolvedBase);
                if (carrier == null)
                    continue;

                carrierLookup[chain.Analysis.ExecutionSite.UniqueId] = (carrier, chain);
                foreach (var clause in chain.Analysis.Clauses)
                {
                    carrierClauseLookup[clause.Site.UniqueId] = (carrier, chain);
                }

                var chainRootClause = chain.Analysis.Clauses
                    .FirstOrDefault(c => c.Role == ClauseRole.ChainRoot);
                if (chainRootClause != null)
                {
                    carrierFirstClauseIds.Add(chainRootClause.Site.UniqueId);
                }
                else if (chain.Analysis.Clauses.Count > 0)
                {
                    carrierFirstClauseIds.Add(chain.Analysis.Clauses[0].Site.UniqueId);
                }

                CarrierEmitter.EmitCarrierClass(sb, carrier);
                carrierIndex++;
            }
        }

        // File-scoped interceptor class
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated interceptors for {_contextClassName} query methods.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"file static class {_contextClassName}Interceptors_{_fileTag}");
        sb.AppendLine("{");

        // Build chain analysis lookups for execution interceptor generation
        var chainLookup = new Dictionary<string, PrebuiltChainInfo>();
        var clauseBitMap = new Dictionary<string, int>();
        var chainMemberIds = new HashSet<string>();
        if (_chains != null)
        {
            foreach (var chain in _chains)
            {
                chainLookup[chain.Analysis.ExecutionSite.UniqueId] = chain;
                chainMemberIds.Add(chain.Analysis.ExecutionSite.UniqueId);
                foreach (var clause in chain.Analysis.Clauses)
                {
                    chainMemberIds.Add(clause.Site.UniqueId);
                    if (clause.IsConditional && clause.BitIndex.HasValue)
                    {
                        clauseBitMap[clause.Site.UniqueId] = clause.BitIndex.Value;
                    }
                }
            }
        }

        // Build clause → chain lookup
        var chainClauseLookup = new Dictionary<string, PrebuiltChainInfo>();
        var firstClauseIds = new HashSet<string>();
        if (_chains != null)
        {
            foreach (var chain in _chains)
            {
                foreach (var clause in chain.Analysis.Clauses)
                {
                    chainClauseLookup[clause.Site.UniqueId] = chain;
                }
                if (chain.Analysis.Clauses.Count > 0)
                {
                    var firstClause = chain.Analysis.Clauses[0];
                    firstClauseIds.Add(firstClause.Site.UniqueId);
                    if (firstClause.Role == ClauseRole.ChainRoot
                        && !carrierClauseLookup.ContainsKey(firstClause.Site.UniqueId)
                        && chain.Analysis.Clauses.Count > 1)
                    {
                        firstClauseIds.Add(chain.Analysis.Clauses[1].Site.UniqueId);
                    }
                }
            }
        }

        // Collect all static fields needed for cached extractors
        var carrierMemberIds = new HashSet<string>(carrierClauseLookup.Keys);
        var staticFields = InterceptorCodeGenerator.CollectStaticFields(_sites, chainMemberIds);

        // Collect all unique TypeMapping classes
        var mappingInstances = InterceptorCodeGenerator.CollectMappingInstances(_sites, chainMemberIds);

        // Collect all unique EntityReader classes
        var entityReaderInstances = InterceptorCodeGenerator.CollectEntityReaderInstances(_sites, chainMemberIds);

        // Filter out carrier member FieldInfo fields
        var interceptorStaticFields = staticFields
            .Where(f => f.SiteUniqueId == null || !carrierMemberIds.Contains(f.SiteUniqueId))
            .ToList();

        if (interceptorStaticFields.Count > 0 || mappingInstances.Count > 0 || entityReaderInstances.Count > 0)
        {
            sb.AppendLine("    #region Cached Fields");
            sb.AppendLine();
            foreach (var field in interceptorStaticFields)
            {
                sb.AppendLine($"    private static FieldInfo? {field.FieldName};");
            }
            foreach (var mapping in mappingInstances)
            {
                sb.AppendLine($"    private static readonly {mapping.Value} {mapping.Key} = new();");
            }
            foreach (var reader in entityReaderInstances)
            {
                sb.AppendLine($"    private static readonly {reader.Value} {reader.Key} = new();");
            }
            sb.AppendLine();
            sb.AppendLine("    #endregion");
            sb.AppendLine();
        }

        // Build the filtered list of sites for generation
        var allSitesForGeneration = _sites
            .Where(s => s.IsAnalyzable || chainMemberIds.Contains(s.UniqueId))
            .ToList();

        // TRACE: Log filtering results
        sb.AppendLine($"    // TRACE: _sites.Count={_sites.Count} chainMemberIds.Count={chainMemberIds.Count} allSitesForGeneration.Count={allSitesForGeneration.Count}");
        foreach (var s in _sites)
        {
            var inChain = chainMemberIds.Contains(s.UniqueId);
            var included = s.IsAnalyzable || inChain;
            if (!included)
                sb.AppendLine($"    // TRACE FILTERED OUT: Kind={s.Kind} UniqueId={s.UniqueId} IsAnalyzable={s.IsAnalyzable} InChain={inChain} Method={s.MethodName}");
        }
        foreach (var s in allSitesForGeneration)
            sb.AppendLine($"    // TRACE INCLUDED: Kind={s.Kind} UniqueId={s.UniqueId} IsAnalyzable={s.IsAnalyzable} Method={s.MethodName}");
        if (_chains != null)
        {
            sb.AppendLine($"    // TRACE: _chains.Count={_chains.Count}");
            foreach (var ch in _chains)
            {
                sb.AppendLine($"    // TRACE CHAIN: ExecUniqueId={ch.Analysis.ExecutionSite.UniqueId} ExecMethod={ch.Analysis.ExecutionSite.MethodName} Tier={ch.Analysis.Tier}");
            }
        }

        // Group interceptors by chain
        var processedSiteIds = new HashSet<string>();
        var chainGroups = new List<(string Label, List<UsageSiteInfo> Sites, IReadOnlyList<string>? TraceLines)>();
        var siteByUniqueId = allSitesForGeneration.ToDictionary(s => s.UniqueId);

        if (_chains != null)
        {
            foreach (var chain in _chains)
            {
                var chainSites = new List<UsageSiteInfo>();
                foreach (var clause in chain.Analysis.Clauses)
                {
                    if (siteByUniqueId.TryGetValue(clause.Site.UniqueId, out var matchingSite))
                    {
                        chainSites.Add(matchingSite);
                        processedSiteIds.Add(matchingSite.UniqueId);
                    }
                }
                if (siteByUniqueId.TryGetValue(chain.Analysis.ExecutionSite.UniqueId, out var execSite))
                {
                    chainSites.Add(execSite);
                    processedSiteIds.Add(execSite.UniqueId);
                }

                if (chainSites.Count > 0)
                {
                    var execMethod = chain.Analysis.ExecutionSite.MethodName;
                    var label = $"Chain: {execMethod} at line {chain.Analysis.ExecutionSite.Line}";
                    chainGroups.Add((label, chainSites, chain.TraceLines));
                }
            }
        }

        // Remaining sites not part of any chain
        var standaloneSites = allSitesForGeneration
            .Where(s => !processedSiteIds.Contains(s.UniqueId))
            .ToList();

        if (standaloneSites.Count > 0)
        {
            chainGroups.Add(("Standalone Interceptors", standaloneSites, null));
        }

        // Pre-group static fields by method name
        var staticFieldsByMethod = new Dictionary<string, List<InterceptorCodeGenerator.CachedExtractorField>>();
        foreach (var f in staticFields)
        {
            if (!staticFieldsByMethod.TryGetValue(f.MethodName, out var list))
            {
                list = new List<InterceptorCodeGenerator.CachedExtractorField>();
                staticFieldsByMethod[f.MethodName] = list;
            }
            list.Add(f);
        }

        // Generate grouped output
        foreach (var (label, sites, traceLines) in chainGroups)
        {
            // Emit trace comments for traced chains
            if (traceLines != null)
            {
                foreach (var line in traceLines)
                    sb.AppendLine($"    // {line}");
                sb.AppendLine();
            }

            sb.AppendLine($"    #region {label}");
            sb.AppendLine();
            foreach (var site in sites)
            {
                EmitInterceptorMethod(sb, site, staticFields, staticFieldsByMethod, chainLookup, clauseBitMap, chainClauseLookup, firstClauseIds, carrierLookup, carrierClauseLookup, carrierFirstClauseIds);
            }
            sb.AppendLine($"    #endregion");
            sb.AppendLine();
        }

        sb.AppendLine("}"); // Close interceptor class
        sb.AppendLine("}"); // Close namespace

        return sb.ToString();
    }

    /// <summary>
    /// Generates an interceptor method for a usage site.
    /// Handles skip checks, XML docs, [InterceptsLocation] attribute, and dispatches
    /// to the appropriate body emitter.
    /// </summary>
    private static void EmitInterceptorMethod(
        StringBuilder sb,
        UsageSiteInfo site,
        List<InterceptorCodeGenerator.CachedExtractorField> staticFields,
        Dictionary<string, List<InterceptorCodeGenerator.CachedExtractorField>> staticFieldsByMethod,
        Dictionary<string, PrebuiltChainInfo> chainLookup,
        Dictionary<string, int> clauseBitMap,
        Dictionary<string, PrebuiltChainInfo> chainClauseLookup,
        HashSet<string> firstClauseIds,
        Dictionary<string, (CarrierClassInfo Carrier, PrebuiltChainInfo Chain)>? carrierLookup = null,
        Dictionary<string, (CarrierClassInfo Carrier, PrebuiltChainInfo Chain)>? carrierClauseLookup = null,
        HashSet<string>? carrierFirstClauseIds = null)
    {
        // Trace sites are compile-time-only signals — no interceptor generated
        if (site.Kind == InterceptorKind.Trace)
            return;

        // Check if this site belongs to a carrier-optimized chain
        var isCarrierSite = false;
        CarrierClassInfo? carrierInfo = null;
        PrebuiltChainInfo? carrierChain = null;

        if (carrierLookup != null && carrierLookup.TryGetValue(site.UniqueId, out var carrierExec))
        {
            isCarrierSite = true;
            carrierInfo = carrierExec.Carrier;
            carrierChain = carrierExec.Chain;
        }
        else if (carrierClauseLookup != null && carrierClauseLookup.TryGetValue(site.UniqueId, out var carrierClause))
        {
            isCarrierSite = true;
            carrierInfo = carrierClause.Carrier;
            carrierChain = carrierClause.Chain;
        }

        // Check for skippable Select sites BEFORE emitting the attribute
        if (site.Kind == InterceptorKind.Select && InterceptorCodeGenerator.ShouldSkipSelectInterceptor(site))
        {
            return;
        }

        // Limit/Offset/Distinct/WithTimeout: carrier-only on non-carrier path
        if (site.Kind is InterceptorKind.Limit or InterceptorKind.Offset or InterceptorKind.Distinct or InterceptorKind.WithTimeout)
        {
            if (!isCarrierSite)
                return;
        }

        // ChainRoot: carrier-only
        if (site.Kind is InterceptorKind.ChainRoot)
        {
            if (!isCarrierSite)
                return;
        }

        // Transitions: carrier-only
        if (site.Kind is InterceptorKind.DeleteTransition or InterceptorKind.UpdateTransition or InterceptorKind.InsertTransition)
        {
            if (!isCarrierSite)
                return;
        }

        // Execution interceptor validation
        if (site.Kind is InterceptorKind.ExecuteFetchAll or InterceptorKind.ExecuteFetchFirst
            or InterceptorKind.ExecuteFetchFirstOrDefault or InterceptorKind.ExecuteFetchSingle
            or InterceptorKind.ToAsyncEnumerable)
        {
            if (!chainLookup.TryGetValue(site.UniqueId, out var chain))
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} Method={site.MethodName} — NOT in chainLookup (chainLookup has {chainLookup.Count} entries)");
                return;
            }
            if (chain.Analysis.UnmatchedMethodNames != null)
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — UnmatchedMethodNames={string.Join(",", chain.Analysis.UnmatchedMethodNames)}");
                return;
            }
            var rawResult = InterceptorCodeGenerator.ResolveExecutionResultType(site.ResultTypeName, chain.ResultTypeName, chain.ProjectionInfo);
            if (string.IsNullOrEmpty(rawResult))
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — empty result type. site.ResultTypeName={site.ResultTypeName ?? "(null)"} chain.ResultTypeName={chain.ResultTypeName ?? "(null)"} projInfo={chain.ProjectionInfo?.ResultTypeName ?? "(null)"}");
                return;
            }
            if (chain.ReaderDelegateCode == null)
            {
                sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — ReaderDelegateCode is null. QueryKind={chain.QueryKind} ProjInfo={chain.ProjectionInfo != null} ProjCols={chain.ProjectionInfo?.Columns.Count ?? 0}");
                return;
            }
            if (chain.ProjectionInfo != null)
            {
                var hasAmbiguousColumns = chain.ProjectionInfo.Columns.Any(c =>
                    c.SqlExpression != null && !string.IsNullOrEmpty(c.ColumnName));
                if (hasAmbiguousColumns)
                {
                    sb.AppendLine($"    // TRACE SKIPPED TERMINAL: Kind={site.Kind} UniqueId={site.UniqueId} — ambiguous columns. ProjKind={chain.ProjectionInfo.Kind}");
                    foreach (var col in chain.ProjectionInfo.Columns)
                        sb.AppendLine($"    //   Col: Name={col.PropertyName ?? "(null)"} ColumnName={col.ColumnName ?? "(null)"} SqlExpr={col.SqlExpression ?? "(null)"} ClrType={col.ClrType ?? "(null)"}");
                    return;
                }
            }
        }
        else if (site.Kind is InterceptorKind.ExecuteScalar)
        {
            if (!chainLookup.TryGetValue(site.UniqueId, out var scalarChain))
            {
                sb.AppendLine($"    // TRACE SKIPPED SCALAR: Kind={site.Kind} UniqueId={site.UniqueId} — NOT in chainLookup");
                return;
            }
            if (scalarChain.Analysis.UnmatchedMethodNames != null)
                return;
            var rawScalarResult = InterceptorCodeGenerator.ResolveExecutionResultType(site.ResultTypeName, scalarChain.ResultTypeName, scalarChain.ProjectionInfo);
            if (string.IsNullOrEmpty(rawScalarResult))
                return;
        }
        else if (site.Kind is InterceptorKind.ExecuteNonQuery)
        {
            if (!chainLookup.TryGetValue(site.UniqueId, out var nqChain))
            {
                sb.AppendLine($"    // TRACE SKIPPED NONQUERY: Kind={site.Kind} UniqueId={site.UniqueId} — NOT in chainLookup");
                return;
            }
            if (nqChain.SqlMap.Values.Any(v => string.IsNullOrWhiteSpace(v.Sql)
                || (nqChain.QueryKind == QueryKind.Update && v.Sql.Contains("SET  "))))
                return;
        }
        else if (site.Kind is InterceptorKind.ToDiagnostics)
        {
            if (chainLookup.TryGetValue(site.UniqueId, out var diagChain)
                && diagChain.Analysis.UnmatchedMethodNames != null)
                return;
            if (!chainLookup.ContainsKey(site.UniqueId) && site.ResultTypeName != null)
                return;
        }

        // Skip non-translatable clauses on non-carrier path
        if (!isCarrierSite && InterceptorCodeGenerator.ShouldSkipNonTranslatableClause(site))
        {
            return;
        }

        var methodName = $"{site.MethodName}_{site.UniqueId}";

        // Determine chain analysis status for remarks
        PrebuiltChainInfo? chainForRemarks = null;
        chainLookup.TryGetValue(site.UniqueId, out chainForRemarks);
        if (chainForRemarks == null)
            chainClauseLookup.TryGetValue(site.UniqueId, out chainForRemarks);

        // XML documentation
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Intercepts {site.MethodName}() call at {InterceptorCodeGenerator.GetRelativePath(site.FilePath)}:{site.Line}:{site.Column}");
        sb.AppendLine($"    /// </summary>");
        if (chainForRemarks != null)
        {
            var carrierLabel = carrierInfo != null ? ", Carrier-Optimized" : "";
            sb.AppendLine($"    /// <remarks>Chain: Fully Analyzed ({chainForRemarks.Analysis.Tier}{carrierLabel})</remarks>");
        }
        else
            sb.AppendLine($"    /// <remarks>Chain: Not Analyzed (standalone interceptor)</remarks>");

        // InterceptsLocation attribute
        if (!string.IsNullOrEmpty(site.InterceptableLocationData))
        {
            sb.AppendLine($"    [InterceptsLocation({site.InterceptableLocationVersion}, \"{site.InterceptableLocationData}\")]");
        }
        else
        {
            sb.AppendLine($"    // WARNING: Could not generate InterceptsLocation for this call site");
            return;
        }

        // Check if this is on a joined builder type
        var isJoinedBuilder = site.JoinedEntityTypeNames != null && site.JoinedEntityTypeNames.Count >= 2;

        // Look up clause bitmask bit index
        clauseBitMap.TryGetValue(site.UniqueId, out var rawBit);
        int? clauseBit = clauseBitMap.ContainsKey(site.UniqueId) ? rawBit : null;

        // Resolve prebuilt chain membership for clause sites
        chainClauseLookup.TryGetValue(site.UniqueId, out var prebuiltClauseChain);
        var isFirstClauseInChain = prebuiltClauseChain != null && firstClauseIds.Contains(site.UniqueId);

        // For carrier chains, override isFirstInChain
        if (isCarrierSite && carrierFirstClauseIds != null)
        {
            isFirstClauseInChain = carrierFirstClauseIds.Contains(site.UniqueId);
        }

        // Dispatch to body emitters
        switch (site.Kind)
        {
            case InterceptorKind.Select:
                if (isJoinedBuilder)
                    JoinBodyEmitter.EmitJoinedSelect(sb, site, methodName, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                else
                    ClauseBodyEmitter.EmitSelect(sb, site, methodName, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.Where:
                {
                    staticFieldsByMethod.TryGetValue(methodName, out var methodFields);
                    if (isJoinedBuilder)
                        JoinBodyEmitter.EmitJoinedWhere(sb, site, methodName, methodFields, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                    else
                        ClauseBodyEmitter.EmitWhere(sb, site, methodName, methodFields, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                }
                break;

            case InterceptorKind.OrderBy:
            case InterceptorKind.ThenBy:
                if (isJoinedBuilder)
                    JoinBodyEmitter.EmitJoinedOrderBy(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                else
                    ClauseBodyEmitter.EmitOrderBy(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.GroupBy:
                ClauseBodyEmitter.EmitGroupBy(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.Having:
                ClauseBodyEmitter.EmitHaving(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.Set:
                ClauseBodyEmitter.EmitSet(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.Join:
            case InterceptorKind.LeftJoin:
            case InterceptorKind.RightJoin:
                JoinBodyEmitter.EmitJoin(sb, site, methodName, prebuiltClauseChain, isFirstClauseInChain, carrierInfo);
                break;

            case InterceptorKind.ExecuteFetchAll:
            case InterceptorKind.ExecuteFetchFirst:
            case InterceptorKind.ExecuteFetchFirstOrDefault:
            case InterceptorKind.ExecuteFetchSingle:
            case InterceptorKind.ExecuteScalar:
            case InterceptorKind.ToAsyncEnumerable:
                if (chainLookup.TryGetValue(site.UniqueId, out var selectChain))
                {
                    if (selectChain.IsJoinChain)
                        TerminalBodyEmitter.EmitJoinReaderTerminal(sb, site, methodName, selectChain, carrierInfo);
                    else
                        TerminalBodyEmitter.EmitReaderTerminal(sb, site, methodName, selectChain, carrierInfo);
                }
                break;

            case InterceptorKind.ExecuteNonQuery:
                if (chainLookup.TryGetValue(site.UniqueId, out var nonQueryChain))
                    TerminalBodyEmitter.EmitNonQueryTerminal(sb, site, methodName, nonQueryChain, carrierInfo);
                break;

            case InterceptorKind.ToDiagnostics:
                if (chainLookup.TryGetValue(site.UniqueId, out var toDiagChain))
                    TerminalBodyEmitter.EmitDiagnosticsTerminal(sb, site, methodName, toDiagChain, carrierInfo);
                else
                    TerminalBodyEmitter.EmitRuntimeDiagnosticsTerminal(sb, site, methodName);
                break;

            case InterceptorKind.DeleteWhere:
                {
                    staticFieldsByMethod.TryGetValue(methodName, out var deleteMethodFields);
                    ClauseBodyEmitter.EmitModificationWhere(sb, site, methodName, deleteMethodFields, isDelete: true, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                }
                break;

            case InterceptorKind.UpdateSet:
                ClauseBodyEmitter.EmitUpdateSet(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.UpdateSetAction:
                ClauseBodyEmitter.EmitUpdateSetAction(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.UpdateSetPoco:
                ClauseBodyEmitter.EmitUpdateSetPoco(sb, site, methodName, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                break;

            case InterceptorKind.UpdateWhere:
                {
                    staticFieldsByMethod.TryGetValue(methodName, out var updateMethodFields);
                    ClauseBodyEmitter.EmitModificationWhere(sb, site, methodName, updateMethodFields, isDelete: false, clauseBit, prebuiltClauseChain, isFirstClauseInChain, carrier: carrierInfo);
                }
                break;

            case InterceptorKind.InsertExecuteNonQuery:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var insertChain);
                    TerminalBodyEmitter.EmitInsertNonQueryTerminal(sb, site, methodName, insertChain, carrierInfo);
                }
                break;

            case InterceptorKind.InsertExecuteScalar:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var insertScalarChain);
                    TerminalBodyEmitter.EmitInsertScalarTerminal(sb, site, methodName, insertScalarChain, carrierInfo);
                }
                break;

            case InterceptorKind.InsertToDiagnostics:
                {
                    chainLookup.TryGetValue(site.UniqueId, out var insertDiagChain);
                    TerminalBodyEmitter.EmitInsertDiagnosticsTerminal(sb, site, methodName, insertDiagChain, carrierInfo);
                }
                break;

            case InterceptorKind.RawSqlAsync:
                RawSqlBodyEmitter.EmitRawSqlAsync(sb, site, methodName);
                break;

            case InterceptorKind.RawSqlScalarAsync:
                RawSqlBodyEmitter.EmitRawSqlScalarAsync(sb, site, methodName);
                break;

            case InterceptorKind.Limit:
            case InterceptorKind.Offset:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitPagination(sb, site, methodName, carrierInfo, carrierChain);
                break;

            case InterceptorKind.Distinct:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitDistinct(sb, site, methodName, carrierInfo, carrierChain);
                break;

            case InterceptorKind.WithTimeout:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitWithTimeout(sb, site, methodName, carrierInfo, carrierChain);
                break;

            case InterceptorKind.ChainRoot:
                if (carrierInfo != null && carrierChain != null)
                    TransitionBodyEmitter.EmitChainRoot(sb, site, methodName, carrierInfo);
                break;

            case InterceptorKind.DeleteTransition:
            case InterceptorKind.UpdateTransition:
                if (carrierInfo != null)
                    TransitionBodyEmitter.EmitDeleteUpdateTransition(sb, site, methodName);
                break;

            case InterceptorKind.InsertTransition:
                if (carrierInfo != null)
                    TransitionBodyEmitter.EmitInsertTransition(sb, site, methodName, carrierInfo);
                break;

            case InterceptorKind.AllTransition:
                TransitionBodyEmitter.EmitAllTransition(sb, site, methodName, carrierInfo);
                break;

            default:
                InterceptorCodeGenerator.GeneratePlaceholderInterceptor(sb, site, methodName);
                break;
        }

        sb.AppendLine();
    }
}
