// <auto-generated>
// Generated by JoinArityHelpers.tt — do not edit by hand.
// Max join arity: 6
// </auto-generated>

using System;

namespace Quarry.Generators.CodeGen;

/// <summary>
/// Centralizes all arity-dependent logic for joined query builder interfaces.
/// Generated from JoinArityHelpers.tt with MaxJoinArity = 6.
/// </summary>
internal static class JoinArityHelpers
{
    public const int MaxJoinArity = 6;

    /// <summary>
    /// Returns the interface name for the given entity count.
    /// 2 → "IJoinedQueryBuilder", 3 → "IJoinedQueryBuilder3", etc.
    /// </summary>
    public static string GetInterfaceName(int entityCount) => entityCount switch
    {
        2 => "IJoinedQueryBuilder",
        3 => "IJoinedQueryBuilder3",
        4 => "IJoinedQueryBuilder4",
        5 => "IJoinedQueryBuilder5",
        6 => "IJoinedQueryBuilder6",
        _ => throw new ArgumentOutOfRangeException(nameof(entityCount), $"Unsupported entity count: {entityCount}. Max arity is {MaxJoinArity}.")
    };

    /// <summary>
    /// Returns the full generic interface string for the given entity type names.
    /// e.g., ["User", "Order"] → "IJoinedQueryBuilder&lt;User, Order&gt;"
    /// </summary>
    public static string GetGenericInterface(string[] entityTypes)
        => $"{GetInterfaceName(entityTypes.Length)}<{string.Join(", ", entityTypes)}>";

    /// <summary>
    /// Returns the full generic interface string with a result type appended.
    /// e.g., (["User", "Order"], "MyResult") → "IJoinedQueryBuilder&lt;User, Order, MyResult&gt;"
    /// </summary>
    public static string GetGenericInterfaceWithResult(string[] entityTypes, string resultType)
        => $"{GetInterfaceName(entityTypes.Length)}<{string.Join(", ", entityTypes)}, {resultType}>";
}
