using Microsoft.Data.Sqlite;
using Quarry.Migration;

namespace Quarry.Tests.Migration;

/// <summary>
/// End-to-end sample demonstrating the Quarry migration system.
///
/// This simulates the full workflow:
///   1. Define schema as C# classes (Schema subclasses — not shown here, but this is what the tool reads)
///   2. Run `quarry migrate add` which diffs schemas and generates migration + snapshot files
///   3. The source generator produces a MigrateAsync() method that wires everything together
///   4. At runtime, MigrateAsync() calls MigrationRunner.RunAsync() against the real database
///
/// Below we write the migrations by hand (the same code the tool would generate),
/// then execute them against an in-memory SQLite database.
/// </summary>
public class MigrationSampleIntegrationTests
{
    private SqliteConnection _connection = null!;
    private SqlDialect _dialect;

    [SetUp]
    public void SetUp()
    {
        _connection = new SqliteConnection("Data Source=:memory:");
        _connection.Open();
        _dialect = SqlDialect.SQLite;
    }

    [TearDown]
    public void TearDown()
    {
        _connection.Dispose();
    }

    // ===================================================================
    // Migration definitions — these mirror what `quarry migrate add` generates.
    // Each migration has three methods: Upgrade, Downgrade, and Backup.
    // ===================================================================

    // --- Migration 1: Initial schema ---
    // Generated by: quarry migrate add InitialCreate
    // Creates users and posts tables.
    private static class M0001_InitialCreate
    {
        public static void Upgrade(MigrationBuilder builder)
        {
            builder.CreateTable("users", null, t =>
            {
                t.Column("id", c => c.ClrType("int").NotNull());
                t.Column("name", c => c.ClrType("string").Length(100).NotNull());
                t.Column("email", c => c.ClrType("string").Length(200).Nullable());
                t.PrimaryKey("PK_users", "id");
            });

            builder.CreateTable("posts", null, t =>
            {
                t.Column("id", c => c.ClrType("int").NotNull());
                t.Column("user_id", c => c.ClrType("int").NotNull());
                t.Column("title", c => c.ClrType("string").Length(200).NotNull());
                t.Column("body", c => c.ClrType("string").Nullable());
                t.PrimaryKey("PK_posts", "id");
            });
        }

        public static void Downgrade(MigrationBuilder builder)
        {
            builder.DropTable("posts");
            builder.DropTable("users");
        }

        public static void Backup(MigrationBuilder builder) { }
    }

    // --- Migration 2: Add index on users table ---
    // Generated by: quarry migrate add AddEmailIndex
    // The differ detected a new Index property on UserSchema.
    private static class M0002_AddEmailIndex
    {
        public static void Upgrade(MigrationBuilder builder)
        {
            builder.AddIndex("IX_users_email", "users", new[] { "email" }, unique: true);
        }

        public static void Downgrade(MigrationBuilder builder)
        {
            builder.DropIndex("IX_users_email", "users");
        }

        public static void Backup(MigrationBuilder builder) { }
    }

    // --- Migration 3: Add column ---
    // Generated by: quarry migrate add AddUserCreatedAt
    // The differ detected a new Col<DateTime> CreatedAt property on UserSchema.
    private static class M0003_AddUserCreatedAt
    {
        public static void Upgrade(MigrationBuilder builder)
        {
            builder.AddColumn("users", "created_at", c => c.ClrType("DateTime").Nullable());
        }

        public static void Downgrade(MigrationBuilder builder)
        {
            builder.DropColumn("users", "created_at");
        }

        public static void Backup(MigrationBuilder builder) { }
    }

    // --- Migration 4: Drop column via SQLite table rebuild ---
    // Generated by: quarry migrate add DropPostBody
    // The differ detected that Col<string?> Body was removed from PostSchema.
    // For SQLite, this uses the rename-recreate-copy-drop rebuild pattern
    // since SQLite doesn't natively support DROP COLUMN in older versions.
    private static class M0004_DropPostBody
    {
        public static void Upgrade(MigrationBuilder builder)
        {
            builder.DropColumn("posts", "body")
                .WithSourceTable(t =>
                {
                    t.Column("id", c => c.ClrType("int").NotNull());
                    t.Column("user_id", c => c.ClrType("int").NotNull());
                    t.Column("title", c => c.ClrType("string").Length(200).NotNull());
                    t.Column("body", c => c.ClrType("string").Nullable());
                    t.PrimaryKey("PK_posts", "id");
                });
        }

        public static void Downgrade(MigrationBuilder builder)
        {
            builder.AddColumn("posts", "body", c => c.ClrType("string").Nullable());
        }

        public static void Backup(MigrationBuilder builder)
        {
            builder.Sql("CREATE TABLE IF NOT EXISTS \"__quarry_backup_posts\" AS SELECT * FROM \"posts\";");
        }
    }

    // --- Migration 5: Seed data (empty migration created with `quarry migrate add-empty`) ---
    // Uses raw SQL for data operations the diff engine can't express.
    private static class M0005_SeedData
    {
        public static void Upgrade(MigrationBuilder builder)
        {
            builder.Sql("INSERT INTO \"users\" (\"id\", \"name\", \"email\", \"created_at\") VALUES (1, 'Alice', 'alice@example.com', '2026-01-01');");
            builder.Sql("INSERT INTO \"users\" (\"id\", \"name\", \"email\", \"created_at\") VALUES (2, 'Bob', 'bob@example.com', '2026-02-15');");
            builder.Sql("INSERT INTO \"posts\" (\"id\", \"user_id\", \"title\") VALUES (1, 1, 'Hello World');");
            builder.Sql("INSERT INTO \"posts\" (\"id\", \"user_id\", \"title\") VALUES (2, 1, 'Second Post');");
            builder.Sql("INSERT INTO \"posts\" (\"id\", \"user_id\", \"title\") VALUES (3, 2, 'Bob''s First Post');");
        }

        public static void Downgrade(MigrationBuilder builder)
        {
            builder.Sql("DELETE FROM \"posts\";");
            builder.Sql("DELETE FROM \"users\";");
        }

        public static void Backup(MigrationBuilder builder) { }
    }

    // ===================================================================
    // This is what the source generator produces — a MigrateAsync method
    // that wires all migrations into a tuple array for MigrationRunner.
    // ===================================================================

    /// <summary>
    /// Simulates the generated MigrateAsync method.
    /// In a real project, the source generator discovers all [Migration] classes
    /// and produces this wiring code automatically on the QuarryContext partial class.
    /// </summary>
    private async Task MigrateAsync(MigrationOptions? options = null)
    {
        var migrations = new (int Version, string Name,
            Action<MigrationBuilder> Upgrade,
            Action<MigrationBuilder> Downgrade,
            Action<MigrationBuilder> Backup)[]
        {
            (1, "InitialCreate",
                M0001_InitialCreate.Upgrade,
                M0001_InitialCreate.Downgrade,
                M0001_InitialCreate.Backup),
            (2, "AddEmailIndex",
                M0002_AddEmailIndex.Upgrade,
                M0002_AddEmailIndex.Downgrade,
                M0002_AddEmailIndex.Backup),
            (3, "AddUserCreatedAt",
                M0003_AddUserCreatedAt.Upgrade,
                M0003_AddUserCreatedAt.Downgrade,
                M0003_AddUserCreatedAt.Backup),
            (4, "DropPostBody",
                M0004_DropPostBody.Upgrade,
                M0004_DropPostBody.Downgrade,
                M0004_DropPostBody.Backup),
            (5, "SeedData",
                M0005_SeedData.Upgrade,
                M0005_SeedData.Downgrade,
                M0005_SeedData.Backup),
        };

        await MigrationRunner.RunAsync(_connection, _dialect, migrations, options);
    }

    // ===================================================================
    // Helper to read column names from a table via PRAGMA
    // ===================================================================

    private async Task<List<string>> GetColumnNamesAsync(string tableName)
    {
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = $"PRAGMA table_info(\"{tableName}\");";
        using var reader = await cmd.ExecuteReaderAsync();
        var columns = new List<string>();
        while (await reader.ReadAsync())
            columns.Add(reader.GetString(1));
        return columns;
    }

    // ===================================================================
    // Tests demonstrating the migration lifecycle
    // ===================================================================

    [Test]
    public async Task FullUpgrade_CreatesSchemaAndSeedsData()
    {
        // This is what a user calls at application startup:
        //   await db.MigrateAsync(connection);
        var logs = new List<string>();
        await MigrateAsync(new MigrationOptions { Logger = s => logs.Add(s) });

        using var cmd = _connection.CreateCommand();

        // Verify all 5 migrations were applied
        cmd.CommandText = "SELECT COUNT(*) FROM __quarry_migrations;";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(5));

        // Verify tables exist
        cmd.CommandText = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name IN ('users', 'posts');";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(2));

        // Verify unique index exists on users.email
        cmd.CommandText = "SELECT name FROM sqlite_master WHERE type='index' AND name='IX_users_email';";
        Assert.That(await cmd.ExecuteScalarAsync(), Is.EqualTo("IX_users_email"));

        // Verify seed data
        cmd.CommandText = "SELECT COUNT(*) FROM \"users\";";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(2));

        cmd.CommandText = "SELECT COUNT(*) FROM \"posts\";";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(3));

        // Verify the 'body' column was dropped (migration 4)
        var postColumns = await GetColumnNamesAsync("posts");
        Assert.That(postColumns, Does.Contain("id"));
        Assert.That(postColumns, Does.Contain("user_id"));
        Assert.That(postColumns, Does.Contain("title"));
        Assert.That(postColumns, Does.Not.Contain("body"));

        // Verify the created_at column was added (migration 3)
        var userColumns = await GetColumnNamesAsync("users");
        Assert.That(userColumns, Does.Contain("created_at"));

        // Verify meaningful log messages were emitted
        Assert.That(logs, Has.Some.Contains("InitialCreate"));
        Assert.That(logs, Has.Some.Contains("SeedData"));
    }

    [Test]
    public async Task SecondRun_IsIdempotent()
    {
        // First run applies all
        await MigrateAsync();

        // Second run is a no-op (all migrations already applied)
        var logs = new List<string>();
        await MigrateAsync(new MigrationOptions { Logger = s => logs.Add(s) });

        // No "Applying migration" messages should appear
        Assert.That(logs.Where(l => l.Contains("Applying migration")), Is.Empty);

        // Data should still be intact
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = "SELECT \"name\" FROM \"users\" WHERE \"id\" = 1;";
        Assert.That(await cmd.ExecuteScalarAsync(), Is.EqualTo("Alice"));
    }

    [Test]
    public async Task PartialUpgrade_StopsAtTargetVersion()
    {
        // Only apply the first 2 migrations (schema + email index)
        await MigrateAsync(new MigrationOptions { TargetVersion = 2 });

        using var cmd = _connection.CreateCommand();
        cmd.CommandText = "SELECT COUNT(*) FROM __quarry_migrations;";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(2));

        // Tables and index exist, but created_at column does not
        var userColumns = await GetColumnNamesAsync("users");
        Assert.That(userColumns, Does.Not.Contain("created_at"));

        // 'body' column should still exist (migration 4 not applied)
        var postColumns = await GetColumnNamesAsync("posts");
        Assert.That(postColumns, Does.Contain("body"));
    }

    [Test]
    public async Task PartialUpgrade_ThenContinue_AppliesRemaining()
    {
        // Apply first 2 migrations
        await MigrateAsync(new MigrationOptions { TargetVersion = 2 });

        // Later, apply the rest (no target = latest)
        await MigrateAsync();

        using var cmd = _connection.CreateCommand();
        cmd.CommandText = "SELECT COUNT(*) FROM __quarry_migrations;";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(5));

        // Seed data should be present
        cmd.CommandText = "SELECT \"email\" FROM \"users\" WHERE \"id\" = 2;";
        Assert.That(await cmd.ExecuteScalarAsync(), Is.EqualTo("bob@example.com"));
    }

    [Test]
    public async Task Downgrade_RollsBackToTargetVersion()
    {
        // Apply all
        await MigrateAsync();

        // Downgrade to version 2 (removes seed data, body column drop, created_at column)
        var logs = new List<string>();
        await MigrateAsync(new MigrationOptions
        {
            Direction = MigrationDirection.Downgrade,
            TargetVersion = 2,
            Logger = s => logs.Add(s)
        });

        using var cmd = _connection.CreateCommand();

        // Only 2 migrations remain
        cmd.CommandText = "SELECT COUNT(*) FROM __quarry_migrations;";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(2));

        // Seed data should be gone
        cmd.CommandText = "SELECT COUNT(*) FROM \"users\";";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(0));

        // 'body' column should be back (migration 4 was rolled back by AddColumn)
        var postColumns = await GetColumnNamesAsync("posts");
        Assert.That(postColumns, Does.Contain("body"));

        // Log should mention rollbacks
        Assert.That(logs, Has.Some.Contains("Rolling back"));
    }

    [Test]
    public async Task FullDowngrade_RemovesEverything()
    {
        await MigrateAsync();

        // Downgrade to version 0 (remove all migrations)
        await MigrateAsync(new MigrationOptions
        {
            Direction = MigrationDirection.Downgrade,
            TargetVersion = 0
        });

        using var cmd = _connection.CreateCommand();

        // History should be empty
        cmd.CommandText = "SELECT COUNT(*) FROM __quarry_migrations;";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(0));

        // All user tables should be gone
        cmd.CommandText = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name IN ('users', 'posts');";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(0));
    }

    [Test]
    public async Task FullRoundTrip_UpgradeDowngradeReUpgrade()
    {
        // Apply all
        await MigrateAsync();

        // Full downgrade
        await MigrateAsync(new MigrationOptions
        {
            Direction = MigrationDirection.Downgrade,
            TargetVersion = 0
        });

        // Re-apply all
        await MigrateAsync();

        using var cmd = _connection.CreateCommand();

        // Everything should be back
        cmd.CommandText = "SELECT COUNT(*) FROM __quarry_migrations;";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(5));

        cmd.CommandText = "SELECT \"name\" FROM \"users\" WHERE \"id\" = 1;";
        Assert.That(await cmd.ExecuteScalarAsync(), Is.EqualTo("Alice"));

        cmd.CommandText = "SELECT \"title\" FROM \"posts\" WHERE \"id\" = 3;";
        Assert.That(await cmd.ExecuteScalarAsync(), Is.EqualTo("Bob's First Post"));
    }

    [Test]
    public async Task DryRun_LogsSqlWithoutApplying()
    {
        var logs = new List<string>();

        await MigrateAsync(new MigrationOptions
        {
            DryRun = true,
            Logger = s => logs.Add(s)
        });

        // No tables should have been created (except the history table)
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name = 'users';";
        Assert.That((long)(await cmd.ExecuteScalarAsync())!, Is.EqualTo(0));

        // But the SQL should have been logged
        Assert.That(logs, Has.Some.Contains("CREATE TABLE"));
        Assert.That(logs, Has.Some.Contains("users"));
    }

    [Test]
    public async Task BackupEnabled_PreservesDataBeforeDestructiveStep()
    {
        // Apply first 3 migrations (schema + index + created_at)
        await MigrateAsync(new MigrationOptions { TargetVersion = 3 });

        // Insert data into posts (which still has 'body' column)
        using (var insertCmd = _connection.CreateCommand())
        {
            insertCmd.CommandText = "INSERT INTO \"posts\" (\"id\", \"user_id\", \"title\", \"body\") VALUES (10, 1, 'Test', 'Important content');";
            await insertCmd.ExecuteNonQueryAsync();
        }

        // Apply only migration 4 (DropPostBody) with backups enabled — stop before seed data
        await MigrateAsync(new MigrationOptions { TargetVersion = 4, RunBackups = true });

        using var cmd = _connection.CreateCommand();

        // Backup table should exist with original data
        cmd.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name='__quarry_backup_posts';";
        Assert.That(await cmd.ExecuteScalarAsync(), Is.EqualTo("__quarry_backup_posts"));

        // Backup should contain the body column data
        cmd.CommandText = "SELECT \"body\" FROM \"__quarry_backup_posts\" WHERE \"id\" = 10;";
        Assert.That(await cmd.ExecuteScalarAsync(), Is.EqualTo("Important content"));

        // The live posts table should not have body column anymore
        var columns = await GetColumnNamesAsync("posts");
        Assert.That(columns, Does.Not.Contain("body"));
    }

    [Test]
    public async Task MigrationHistory_TracksMetadata()
    {
        await MigrateAsync();

        using var cmd = _connection.CreateCommand();
        cmd.CommandText = "SELECT version, name, applied_by, execution_time_ms FROM __quarry_migrations ORDER BY version;";
        using var reader = await cmd.ExecuteReaderAsync();

        var versions = new List<(int Version, string Name, string AppliedBy, long TimeMs)>();
        while (await reader.ReadAsync())
        {
            versions.Add((
                reader.GetInt32(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetInt64(3)
            ));
        }

        Assert.That(versions, Has.Count.EqualTo(5));
        Assert.That(versions[0].Version, Is.EqualTo(1));
        Assert.That(versions[0].Name, Is.EqualTo("InitialCreate"));
        Assert.That(versions[4].Version, Is.EqualTo(5));
        Assert.That(versions[4].Name, Is.EqualTo("SeedData"));

        // All should have applied_by metadata (machine/user)
        foreach (var v in versions)
        {
            Assert.That(v.AppliedBy, Is.Not.Null.And.Not.Empty);
            Assert.That(v.TimeMs, Is.GreaterThanOrEqualTo(0));
        }
    }
}
