using Microsoft.Data.Sqlite;
using Quarry;
using Quarry.Migration;
using SimpleMigration.Migrations;

// =============================================================================
// Quarry Migration Sample — Interactive Console Demo
//
// Demonstrates the migration runtime against an in-memory SQLite database.
// The migrations in the Migrations/ folder were generated by `quarry migrate add`.
// At runtime, the source generator wires them into a MigrateAsync() method on
// your QuarryContext — here we call MigrationRunner directly to show the mechanics.
// =============================================================================

var connection = new SqliteConnection("Data Source=:memory:");
connection.Open();

var dialect = SqlDialect.SQLite;

// ─── Migration Definitions ──────────────────────────────────────────────────
// These reference the generated migration classes in the Migrations/ folder,
// produced by `quarry migrate add <name>`.
// ─────────────────────────────────────────────────────────────────────────────

var migrations = new (int Version, string Name,
    Action<MigrationBuilder> Upgrade,
    Action<MigrationBuilder> Downgrade,
    Action<MigrationBuilder> Backup)[]
{
    (1, "InitialCreate",
        M0001_InitialCreate.Upgrade,
        M0001_InitialCreate.Downgrade,
        M0001_InitialCreate.Backup),

    (2, "AddEmailAndIndex",
        M0002_AddEmailAndIndex.Upgrade,
        M0002_AddEmailAndIndex.Downgrade,
        M0002_AddEmailAndIndex.Backup),

    (3, "AddTimestampsAndIsActive",
        M0003_AddTimestampsAndIsActive.Upgrade,
        M0003_AddTimestampsAndIsActive.Downgrade,
        M0003_AddTimestampsAndIsActive.Backup),
};

// ─── Interactive Menu ───────────────────────────────────────────────────────

Console.Clear();
PrintHeader();
ShowStatus(connection);

while (true)
{
    Console.WriteLine();
    WriteColor("  [1]", ConsoleColor.Yellow); Console.WriteLine(" Migrate (upgrade to latest)");
    WriteColor("  [2]", ConsoleColor.Yellow); Console.WriteLine(" Revert  (downgrade one version)");
    WriteColor("  [3]", ConsoleColor.Yellow); Console.WriteLine(" Reset   (downgrade to version 0, 1, or 2)");
    WriteColor("  [4]", ConsoleColor.Yellow); Console.WriteLine(" Status  (show current schema & data)");
    WriteColor("  [5]", ConsoleColor.Yellow); Console.WriteLine(" History (show migration history table)");
    WriteColor("  [6]", ConsoleColor.Yellow); Console.WriteLine(" Preview (dry-run next migration SQL)");
    WriteColor("  [7]", ConsoleColor.Yellow); Console.WriteLine(" Data    (query table contents)");
    WriteColor("  [Q]", ConsoleColor.Yellow); Console.WriteLine(" Quit");
    Console.WriteLine();
    Console.Write("  > ");

    var input = Console.ReadLine()?.Trim().ToUpperInvariant();
    Console.WriteLine();

    switch (input)
    {
        case "1":
            await RunMigrate(connection, dialect, migrations);
            break;
        case "2":
            await RunRevert(connection, dialect, migrations);
            break;
        case "3":
            await RunReset(connection, dialect, migrations);
            break;
        case "4":
            ShowStatus(connection);
            break;
        case "5":
            PreviewNextMigration(connection, dialect, migrations);
            break;
        case "6":
            await ShowHistory(connection);
            break;
        case "7":
            await QueryData(connection);
            break;
        case "Q":
            connection.Dispose();
            WriteColor("  Goodbye!\n", ConsoleColor.DarkGray);
            return;
        default:
            WriteColor("  Invalid option.\n", ConsoleColor.Red);
            break;
    }
}

// ─── Commands ───────────────────────────────────────────────────────────────

static async Task RunMigrate(
    SqliteConnection connection, SqlDialect dialect,
    (int, string, Action<MigrationBuilder>, Action<MigrationBuilder>, Action<MigrationBuilder>)[] migrations)
{
    var currentVersion = await GetCurrentVersion(connection);
    if (currentVersion >= migrations.Length)
    {
        WriteColor("  Already at latest version. Nothing to do.\n", ConsoleColor.DarkGray);
        return;
    }

    WriteColor($"  Upgrading from version {currentVersion} to {migrations.Length}...\n", ConsoleColor.Cyan);

    await MigrationRunner.RunAsync(connection, dialect, migrations,
        new MigrationOptions { Logger = s => WriteColor($"    {s}\n", ConsoleColor.DarkGray) });

    WriteColor("  Done.\n", ConsoleColor.Green);
    ShowStatus(connection);
}

static async Task RunRevert(
    SqliteConnection connection, SqlDialect dialect,
    (int, string, Action<MigrationBuilder>, Action<MigrationBuilder>, Action<MigrationBuilder>)[] migrations)
{
    var currentVersion = await GetCurrentVersion(connection);
    if (currentVersion == 0)
    {
        WriteColor("  Already at version 0. Nothing to revert.\n", ConsoleColor.DarkGray);
        return;
    }

    var target = currentVersion - 1;
    WriteColor($"  Reverting from version {currentVersion} to {target}...\n", ConsoleColor.Cyan);

    await MigrationRunner.RunAsync(connection, dialect, migrations,
        new MigrationOptions
        {
            Direction = MigrationDirection.Downgrade,
            TargetVersion = target,
            Logger = s => WriteColor($"    {s}\n", ConsoleColor.DarkGray)
        });

    WriteColor("  Done.\n", ConsoleColor.Green);
    ShowStatus(connection);
}

static async Task RunReset(
    SqliteConnection connection, SqlDialect dialect,
    (int, string, Action<MigrationBuilder>, Action<MigrationBuilder>, Action<MigrationBuilder>)[] migrations)
{
    Console.Write("  Reset to version [0, 1, or 2]: ");
    var input = Console.ReadLine()?.Trim();
    if (!int.TryParse(input, out var target) || target < 0 || target > 2)
    {
        WriteColor("  Invalid version. Must be 0, 1, or 2.\n", ConsoleColor.Red);
        return;
    }

    var currentVersion = await GetCurrentVersion(connection);

    if (target == currentVersion)
    {
        WriteColor($"  Already at version {target}.\n", ConsoleColor.DarkGray);
        return;
    }

    if (target < currentVersion)
    {
        WriteColor($"  Downgrading from version {currentVersion} to {target}...\n", ConsoleColor.Cyan);
        await MigrationRunner.RunAsync(connection, dialect, migrations,
            new MigrationOptions
            {
                Direction = MigrationDirection.Downgrade,
                TargetVersion = target,
                Logger = s => WriteColor($"    {s}\n", ConsoleColor.DarkGray)
            });
    }
    else
    {
        WriteColor($"  Upgrading from version {currentVersion} to {target}...\n", ConsoleColor.Cyan);
        await MigrationRunner.RunAsync(connection, dialect, migrations,
            new MigrationOptions
            {
                TargetVersion = target,
                Logger = s => WriteColor($"    {s}\n", ConsoleColor.DarkGray)
            });
    }

    WriteColor("  Done.\n", ConsoleColor.Green);
    ShowStatus(connection);
}

static void ShowStatus(SqliteConnection connection)
{
    Console.WriteLine("  ┌──────────────────────────────────────────────┐");

    var version = GetCurrentVersionSync(connection);
    Console.Write("  │ ");
    WriteColor("Database Version: ", ConsoleColor.White);
    WriteColor($"{version}", version == 0 ? ConsoleColor.Red : ConsoleColor.Green);
    var maxVersion = 3;
    WriteColor($" / {maxVersion}", ConsoleColor.DarkGray);
    Console.WriteLine(new string(' ', 46 - 22 - version.ToString().Length - maxVersion.ToString().Length) + "│");

    // List tables
    using var cmd = connection.CreateCommand();
    cmd.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;";
    using var reader = cmd.ExecuteReader();
    var tables = new List<string>();
    while (reader.Read())
        tables.Add(reader.GetString(0));
    reader.Close();

    Console.Write("  │ ");
    WriteColor("Tables: ", ConsoleColor.White);
    if (tables.Count == 0)
    {
        WriteColor("(none)", ConsoleColor.DarkGray);
        Console.WriteLine(new string(' ', 46 - 14) + "│");
    }
    else
    {
        var tableStr = string.Join(", ", tables.Where(t => !t.StartsWith("__quarry")));
        var truncated = tableStr.Length > 32 ? tableStr[..32] + "..." : tableStr;
        Console.Write(truncated);
        Console.WriteLine(new string(' ', Math.Max(0, 46 - 10 - truncated.Length)) + "│");
    }

    // List columns for each user table
    foreach (var table in tables.Where(t => !t.StartsWith("__quarry")))
    {
        using var colCmd = connection.CreateCommand();
        colCmd.CommandText = $"PRAGMA table_info(\"{table}\");";
        using var colReader = colCmd.ExecuteReader();
        var cols = new List<string>();
        while (colReader.Read())
            cols.Add(colReader.GetString(1));
        colReader.Close();

        Console.Write("  │   ");
        WriteColor($"{table}", ConsoleColor.DarkYellow);
        Console.Write(": ");
        var colStr = string.Join(", ", cols);
        var maxLen = 46 - 5 - table.Length - 2;
        var display = colStr.Length > maxLen ? colStr[..maxLen] + "..." : colStr;
        Console.Write(display);
        Console.WriteLine(new string(' ', Math.Max(0, maxLen - display.Length)) + "│");
    }

    // Row counts
    foreach (var table in tables.Where(t => !t.StartsWith("__quarry")))
    {
        using var countCmd = connection.CreateCommand();
        countCmd.CommandText = $"SELECT COUNT(*) FROM \"{table}\";";
        var count = (long)countCmd.ExecuteScalar()!;
        Console.Write("  │     ");
        WriteColor($"→ {count} row{(count != 1 ? "s" : "")}", ConsoleColor.DarkGray);
        var rowStr = $"→ {count} row{(count != 1 ? "s" : "")}";
        Console.WriteLine(new string(' ', Math.Max(0, 46 - 7 - rowStr.Length)) + "│");
    }

    // Indexes
    using var idxCmd = connection.CreateCommand();
    idxCmd.CommandText = "SELECT name FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%' ORDER BY name;";
    using var idxReader = idxCmd.ExecuteReader();
    var indexes = new List<string>();
    while (idxReader.Read())
        indexes.Add(idxReader.GetString(0));
    idxReader.Close();

    if (indexes.Count > 0)
    {
        Console.Write("  │ ");
        WriteColor("Indexes: ", ConsoleColor.White);
        var idxStr = string.Join(", ", indexes);
        var idxMax = 46 - 11;
        var idxDisplay = idxStr.Length > idxMax ? idxStr[..idxMax] + "..." : idxStr;
        Console.Write(idxDisplay);
        Console.WriteLine(new string(' ', Math.Max(0, idxMax - idxDisplay.Length)) + "│");
    }

    Console.WriteLine("  └──────────────────────────────────────────────┘");
}

static async Task ShowHistory(SqliteConnection connection)
{
    // Check if history table exists
    using var checkCmd = connection.CreateCommand();
    checkCmd.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name='__quarry_migrations';";
    if (await checkCmd.ExecuteScalarAsync() == null)
    {
        WriteColor("  No migration history (database not initialized).\n", ConsoleColor.DarkGray);
        return;
    }

    using var cmd = connection.CreateCommand();
    cmd.CommandText = "SELECT version, name, applied_at, execution_time_ms, applied_by FROM __quarry_migrations ORDER BY version;";
    using var reader = await cmd.ExecuteReaderAsync();

    Console.WriteLine("  ┌─────────┬──────────────────────┬─────────────────────────┬────────┐");
    Console.WriteLine("  │ Version │ Name                 │ Applied At              │ Time   │");
    Console.WriteLine("  ├─────────┼──────────────────────┼─────────────────────────┼────────┤");

    var hasRows = false;
    while (await reader.ReadAsync())
    {
        hasRows = true;
        var ver = reader.GetInt32(0);
        var name = reader.GetString(1);
        var appliedAt = reader.GetString(2);
        var timeMs = reader.GetInt64(3);

        // Truncate for display
        if (name.Length > 20) name = name[..17] + "...";
        if (appliedAt.Length > 23) appliedAt = appliedAt[..23];

        Console.Write("  │ ");
        WriteColor($"{ver,7}", ConsoleColor.Green);
        Console.Write($" │ {name,-20} │ {appliedAt,-23} │ ");
        WriteColor($"{timeMs,3}", ConsoleColor.Cyan);
        Console.WriteLine(" ms │");
    }

    if (!hasRows)
    {
        Console.WriteLine("  │                         (empty)                          │");
    }

    Console.WriteLine("  └─────────┴──────────────────────┴─────────────────────────┴────────┘");
}

static void PreviewNextMigration(
    SqliteConnection connection, SqlDialect dialect,
    (int Version, string Name, Action<MigrationBuilder> Upgrade, Action<MigrationBuilder> Downgrade, Action<MigrationBuilder> Backup)[] migrations)
{
    var currentVersion = GetCurrentVersionSync(connection);
    if (currentVersion >= migrations.Length)
    {
        WriteColor("  Already at latest version. Nothing to preview.\n", ConsoleColor.DarkGray);
        return;
    }

    var next = migrations[currentVersion]; // 0-indexed, version is 1-indexed
    WriteColor($"  Preview of migration {next.Version}: {next.Name}\n", ConsoleColor.Cyan);
    Console.WriteLine("  " + new string('─', 60));

    var builder = new MigrationBuilder();
    next.Upgrade(builder);
    var sql = builder.BuildSql(dialect);

    foreach (var line in sql.Split('\n'))
    {
        Console.Write("  ");
        // Colorize SQL keywords
        var trimmed = line.TrimEnd();
        if (trimmed.StartsWith("CREATE TABLE", StringComparison.OrdinalIgnoreCase) ||
            trimmed.StartsWith("ALTER TABLE", StringComparison.OrdinalIgnoreCase) ||
            trimmed.StartsWith("DROP TABLE", StringComparison.OrdinalIgnoreCase) ||
            trimmed.StartsWith("CREATE UNIQUE INDEX", StringComparison.OrdinalIgnoreCase) ||
            trimmed.StartsWith("CREATE INDEX", StringComparison.OrdinalIgnoreCase) ||
            trimmed.StartsWith("INSERT INTO", StringComparison.OrdinalIgnoreCase))
        {
            WriteColor(trimmed + "\n", ConsoleColor.Yellow);
        }
        else
        {
            Console.WriteLine(trimmed);
        }
    }

    Console.WriteLine("  " + new string('─', 60));
}

static async Task QueryData(SqliteConnection connection)
{
    // Find user tables
    using var tablesCmd = connection.CreateCommand();
    tablesCmd.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '__quarry%' ORDER BY name;";
    using var tablesReader = await tablesCmd.ExecuteReaderAsync();
    var tables = new List<string>();
    while (await tablesReader.ReadAsync())
        tables.Add(tablesReader.GetString(0));
    await tablesReader.CloseAsync();

    if (tables.Count == 0)
    {
        WriteColor("  No tables exist. Run a migration first.\n", ConsoleColor.DarkGray);
        return;
    }

    foreach (var table in tables)
    {
        WriteColor($"\n  {table}\n", ConsoleColor.Cyan);

        using var cmd = connection.CreateCommand();
        cmd.CommandText = $"SELECT * FROM \"{table}\";";
        using var reader = await cmd.ExecuteReaderAsync();

        // Header
        var widths = new int[reader.FieldCount];
        var headers = new string[reader.FieldCount];
        for (var i = 0; i < reader.FieldCount; i++)
        {
            headers[i] = reader.GetName(i);
            widths[i] = Math.Max(headers[i].Length, 4);
        }

        // Read all rows to determine column widths
        var rows = new List<string[]>();
        while (await reader.ReadAsync())
        {
            var row = new string[reader.FieldCount];
            for (var i = 0; i < reader.FieldCount; i++)
            {
                row[i] = reader.IsDBNull(i) ? "(null)" : reader.GetValue(i).ToString() ?? "";
                widths[i] = Math.Min(Math.Max(widths[i], row[i].Length), 25);
            }
            rows.Add(row);
        }

        // Print header
        Console.Write("  ");
        for (var i = 0; i < headers.Length; i++)
        {
            if (i > 0) Console.Write(" │ ");
            WriteColor(Pad(headers[i], widths[i]), ConsoleColor.White);
        }
        Console.WriteLine();

        // Separator
        Console.Write("  ");
        for (var i = 0; i < headers.Length; i++)
        {
            if (i > 0) Console.Write("─┼─");
            Console.Write(new string('─', widths[i]));
        }
        Console.WriteLine();

        // Rows
        if (rows.Count == 0)
        {
            WriteColor("  (no rows)\n", ConsoleColor.DarkGray);
        }
        else
        {
            foreach (var row in rows)
            {
                Console.Write("  ");
                for (var i = 0; i < row.Length; i++)
                {
                    if (i > 0) Console.Write(" │ ");
                    var val = row[i].Length > widths[i] ? row[i][..(widths[i] - 3)] + "..." : row[i];
                    if (val == "(null)")
                        WriteColor(Pad(val, widths[i]), ConsoleColor.DarkGray);
                    else
                        Console.Write(Pad(val, widths[i]));
                }
                Console.WriteLine();
            }
        }

        Console.WriteLine($"  ({rows.Count} row{(rows.Count != 1 ? "s" : "")})");
    }
}

// ─── Helpers ────────────────────────────────────────────────────────────────

static async Task<int> GetCurrentVersion(SqliteConnection connection)
{
    using var checkCmd = connection.CreateCommand();
    checkCmd.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name='__quarry_migrations';";
    if (await checkCmd.ExecuteScalarAsync() == null)
        return 0;

    using var cmd = connection.CreateCommand();
    cmd.CommandText = "SELECT COALESCE(MAX(version), 0) FROM __quarry_migrations;";
    return Convert.ToInt32(await cmd.ExecuteScalarAsync());
}

static int GetCurrentVersionSync(SqliteConnection connection)
{
    using var checkCmd = connection.CreateCommand();
    checkCmd.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name='__quarry_migrations';";
    if (checkCmd.ExecuteScalar() == null)
        return 0;

    using var cmd = connection.CreateCommand();
    cmd.CommandText = "SELECT COALESCE(MAX(version), 0) FROM __quarry_migrations;";
    return Convert.ToInt32(cmd.ExecuteScalar());
}

static void PrintHeader()
{
    WriteColor(@"
   ____                              __  __ _                 _   _
  / __ \                            |  \/  (_)               | | (_)
 | |  | |_   _  __ _ _ __ _ __ _   | \  / |_  __ _ _ __ __ _| |_ _  ___  _ __
 | |  | | | | |/ _` | '__| '__| | | | |\/| | |/ _` | '__/ _` | __| |/ _ \| '_ \
 | |__| | |_| | (_| | |  | |  | |_| | |  | | | (_| | | | (_| | |_| | (_) | | | |
  \___\_\\__,_|\__,_|_|  |_|   \__, |_|  |_|_|\__, |_|  \__,_|\__|_|\___/|_| |_|
                                 __/ |          __/ |
                                |___/          |___/
", ConsoleColor.Cyan);
    Console.WriteLine("  Interactive SQLite migration demo");
    Console.WriteLine("  Using in-memory database with 3 tool-generated migrations");
    Console.WriteLine();
}

static void WriteColor(string text, ConsoleColor color)
{
    var prev = Console.ForegroundColor;
    Console.ForegroundColor = color;
    Console.Write(text);
    Console.ForegroundColor = prev;
}

static string Pad(string text, int width)
{
    return text.Length >= width ? text[..width] : text + new string(' ', width - text.Length);
}
